import { Drill } from '../drillLibrary';

// Auto-generated expanded code drills
export const codeDrillPacks: Record<string, Drill[]> = {
    "typescript": [
        {
            "id": "code_ts_1",
            "specialty": "TypeScript",
            "tier": "INTERMEDIATE",
            "title": "TypeScript Practice 1",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 64,
            "content": "export class Queue<T> {\n  private data: T[] = [];\n  push(item: T) { this.data.push(item); }\n  pop(): T | undefined { return this.data.shift(); }\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for TypeScript."
        },
        {
            "id": "code_ts_2",
            "specialty": "TypeScript",
            "tier": "INTERMEDIATE",
            "title": "TypeScript Practice 2",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 64,
            "content": "export class Queue<T> {\n  private data: T[] = [];\n  push(item: T) { this.data.push(item); }\n  pop(): T | undefined { return this.data.shift(); }\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for TypeScript."
        },
        {
            "id": "code_ts_3",
            "specialty": "TypeScript",
            "tier": "INTERMEDIATE",
            "title": "TypeScript Practice 3",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 59,
            "content": "export class Queue<T> {\n  private data: T[] = [];\n  push(item: T) { this.data.push(item); }\n  pop(): T | undefined { return this.data.shift(); }\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for TypeScript."
        },
        {
            "id": "code_ts_4",
            "specialty": "TypeScript",
            "tier": "CORE",
            "title": "TypeScript Practice 4",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 53,
            "content": "const items = [1, 2, 3, 4, 5];\nconst doubledItems = items.map(item => item * 2);\nconsole.log(doubledItems.filter(n => n > 5));",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for TypeScript."
        },
        {
            "id": "code_ts_5",
            "specialty": "TypeScript",
            "tier": "CORE",
            "title": "TypeScript Practice 5",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 62,
            "content": "interface User { id: string; name: string; age?: number; }\nconst getUser = async (id: string): Promise<User> => {\n  const res = await fetch(`/api/users/${id}`);\n  return res.json();\n};",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for TypeScript."
        },
        {
            "id": "code_ts_6",
            "specialty": "TypeScript",
            "tier": "INTERMEDIATE",
            "title": "TypeScript Practice 6",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 69,
            "content": "const items = [1, 2, 3, 4, 5];\nconst doubledItems = items.map(item => item * 2);\nconsole.log(doubledItems.filter(n => n > 5));",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for TypeScript."
        },
        {
            "id": "code_ts_7",
            "specialty": "TypeScript",
            "tier": "INTERMEDIATE",
            "title": "TypeScript Practice 7",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 60,
            "content": "export class Queue<T> {\n  private data: T[] = [];\n  push(item: T) { this.data.push(item); }\n  pop(): T | undefined { return this.data.shift(); }\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for TypeScript."
        },
        {
            "id": "code_ts_8",
            "specialty": "TypeScript",
            "tier": "INTERMEDIATE",
            "title": "TypeScript Practice 8",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 58,
            "content": "interface User { id: string; name: string; age?: number; }\nconst getUser = async (id: string): Promise<User> => {\n  const res = await fetch(`/api/users/${id}`);\n  return res.json();\n};",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for TypeScript."
        },
        {
            "id": "code_ts_9",
            "specialty": "TypeScript",
            "tier": "CORE",
            "title": "TypeScript Practice 9",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 59,
            "content": "const items = [1, 2, 3, 4, 5];\nconst doubledItems = items.map(item => item * 2);\nconsole.log(doubledItems.filter(n => n > 5));",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for TypeScript."
        },
        {
            "id": "code_ts_10",
            "specialty": "TypeScript",
            "tier": "INTERMEDIATE",
            "title": "TypeScript Practice 10",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 62,
            "content": "export class Queue<T> {\n  private data: T[] = [];\n  push(item: T) { this.data.push(item); }\n  pop(): T | undefined { return this.data.shift(); }\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for TypeScript."
        },
        {
            "id": "code_ts_11",
            "specialty": "TypeScript",
            "tier": "INTERMEDIATE",
            "title": "TypeScript Practice 11",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 63,
            "content": "const items = [1, 2, 3, 4, 5];\nconst doubledItems = items.map(item => item * 2);\nconsole.log(doubledItems.filter(n => n > 5));",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for TypeScript."
        },
        {
            "id": "code_ts_12",
            "specialty": "TypeScript",
            "tier": "CORE",
            "title": "TypeScript Practice 12",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 65,
            "content": "export class Queue<T> {\n  private data: T[] = [];\n  push(item: T) { this.data.push(item); }\n  pop(): T | undefined { return this.data.shift(); }\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for TypeScript."
        },
        {
            "id": "code_ts_13",
            "specialty": "TypeScript",
            "tier": "INTERMEDIATE",
            "title": "TypeScript Practice 13",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 51,
            "content": "export class Queue<T> {\n  private data: T[] = [];\n  push(item: T) { this.data.push(item); }\n  pop(): T | undefined { return this.data.shift(); }\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for TypeScript."
        },
        {
            "id": "code_ts_14",
            "specialty": "TypeScript",
            "tier": "CORE",
            "title": "TypeScript Practice 14",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 50,
            "content": "export class Queue<T> {\n  private data: T[] = [];\n  push(item: T) { this.data.push(item); }\n  pop(): T | undefined { return this.data.shift(); }\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for TypeScript."
        },
        {
            "id": "code_ts_15",
            "specialty": "TypeScript",
            "tier": "INTERMEDIATE",
            "title": "TypeScript Practice 15",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 68,
            "content": "const items = [1, 2, 3, 4, 5];\nconst doubledItems = items.map(item => item * 2);\nconsole.log(doubledItems.filter(n => n > 5));",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for TypeScript."
        },
        {
            "id": "code_ts_16",
            "specialty": "TypeScript",
            "tier": "CORE",
            "title": "TypeScript Practice 16",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 68,
            "content": "const items = [1, 2, 3, 4, 5];\nconst doubledItems = items.map(item => item * 2);\nconsole.log(doubledItems.filter(n => n > 5));",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for TypeScript."
        },
        {
            "id": "code_ts_17",
            "specialty": "TypeScript",
            "tier": "CORE",
            "title": "TypeScript Practice 17",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 67,
            "content": "const items = [1, 2, 3, 4, 5];\nconst doubledItems = items.map(item => item * 2);\nconsole.log(doubledItems.filter(n => n > 5));",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for TypeScript."
        },
        {
            "id": "code_ts_18",
            "specialty": "TypeScript",
            "tier": "INTERMEDIATE",
            "title": "TypeScript Practice 18",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 69,
            "content": "interface User { id: string; name: string; age?: number; }\nconst getUser = async (id: string): Promise<User> => {\n  const res = await fetch(`/api/users/${id}`);\n  return res.json();\n};",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for TypeScript."
        },
        {
            "id": "code_ts_19",
            "specialty": "TypeScript",
            "tier": "CORE",
            "title": "TypeScript Practice 19",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 67,
            "content": "export class Queue<T> {\n  private data: T[] = [];\n  push(item: T) { this.data.push(item); }\n  pop(): T | undefined { return this.data.shift(); }\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for TypeScript."
        },
        {
            "id": "code_ts_20",
            "specialty": "TypeScript",
            "tier": "CORE",
            "title": "TypeScript Practice 20",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 66,
            "content": "const items = [1, 2, 3, 4, 5];\nconst doubledItems = items.map(item => item * 2);\nconsole.log(doubledItems.filter(n => n > 5));",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for TypeScript."
        }
    ],
    "python": [
        {
            "id": "code_py_1",
            "specialty": "Python",
            "tier": "INTERMEDIATE",
            "title": "Python Practice 1",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 51,
            "content": "class Animal:\n    def __init__(self, name):\n        self.name = name\n\n    def speak(self):\n        pass",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Python."
        },
        {
            "id": "code_py_2",
            "specialty": "Python",
            "tier": "CORE",
            "title": "Python Practice 2",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 63,
            "content": "class Animal:\n    def __init__(self, name):\n        self.name = name\n\n    def speak(self):\n        pass",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Python."
        },
        {
            "id": "code_py_3",
            "specialty": "Python",
            "tier": "INTERMEDIATE",
            "title": "Python Practice 3",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 62,
            "content": "import pandas as pd\n\ndf = pd.read_csv('data.csv')\nfiltered_df = df[df['age'] > 30]\nprint(filtered_df.describe())",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Python."
        },
        {
            "id": "code_py_4",
            "specialty": "Python",
            "tier": "CORE",
            "title": "Python Practice 4",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 66,
            "content": "class Animal:\n    def __init__(self, name):\n        self.name = name\n\n    def speak(self):\n        pass",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Python."
        },
        {
            "id": "code_py_5",
            "specialty": "Python",
            "tier": "CORE",
            "title": "Python Practice 5",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 69,
            "content": "def calculate_fibonacci(n):\n    if n <= 1:\n        return n\n    return calculate_fibonacci(n-1) + calculate_fibonacci(n-2)",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Python."
        },
        {
            "id": "code_py_6",
            "specialty": "Python",
            "tier": "INTERMEDIATE",
            "title": "Python Practice 6",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 66,
            "content": "import pandas as pd\n\ndf = pd.read_csv('data.csv')\nfiltered_df = df[df['age'] > 30]\nprint(filtered_df.describe())",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Python."
        },
        {
            "id": "code_py_7",
            "specialty": "Python",
            "tier": "INTERMEDIATE",
            "title": "Python Practice 7",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 60,
            "content": "import pandas as pd\n\ndf = pd.read_csv('data.csv')\nfiltered_df = df[df['age'] > 30]\nprint(filtered_df.describe())",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Python."
        },
        {
            "id": "code_py_8",
            "specialty": "Python",
            "tier": "INTERMEDIATE",
            "title": "Python Practice 8",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 50,
            "content": "def calculate_fibonacci(n):\n    if n <= 1:\n        return n\n    return calculate_fibonacci(n-1) + calculate_fibonacci(n-2)",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Python."
        },
        {
            "id": "code_py_9",
            "specialty": "Python",
            "tier": "CORE",
            "title": "Python Practice 9",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 54,
            "content": "def calculate_fibonacci(n):\n    if n <= 1:\n        return n\n    return calculate_fibonacci(n-1) + calculate_fibonacci(n-2)",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Python."
        },
        {
            "id": "code_py_10",
            "specialty": "Python",
            "tier": "INTERMEDIATE",
            "title": "Python Practice 10",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 69,
            "content": "def calculate_fibonacci(n):\n    if n <= 1:\n        return n\n    return calculate_fibonacci(n-1) + calculate_fibonacci(n-2)",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Python."
        },
        {
            "id": "code_py_11",
            "specialty": "Python",
            "tier": "INTERMEDIATE",
            "title": "Python Practice 11",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 66,
            "content": "class Animal:\n    def __init__(self, name):\n        self.name = name\n\n    def speak(self):\n        pass",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Python."
        },
        {
            "id": "code_py_12",
            "specialty": "Python",
            "tier": "CORE",
            "title": "Python Practice 12",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 53,
            "content": "import pandas as pd\n\ndf = pd.read_csv('data.csv')\nfiltered_df = df[df['age'] > 30]\nprint(filtered_df.describe())",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Python."
        },
        {
            "id": "code_py_13",
            "specialty": "Python",
            "tier": "INTERMEDIATE",
            "title": "Python Practice 13",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 56,
            "content": "def calculate_fibonacci(n):\n    if n <= 1:\n        return n\n    return calculate_fibonacci(n-1) + calculate_fibonacci(n-2)",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Python."
        },
        {
            "id": "code_py_14",
            "specialty": "Python",
            "tier": "CORE",
            "title": "Python Practice 14",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 59,
            "content": "class Animal:\n    def __init__(self, name):\n        self.name = name\n\n    def speak(self):\n        pass",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Python."
        },
        {
            "id": "code_py_15",
            "specialty": "Python",
            "tier": "INTERMEDIATE",
            "title": "Python Practice 15",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 64,
            "content": "def calculate_fibonacci(n):\n    if n <= 1:\n        return n\n    return calculate_fibonacci(n-1) + calculate_fibonacci(n-2)",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Python."
        },
        {
            "id": "code_py_16",
            "specialty": "Python",
            "tier": "CORE",
            "title": "Python Practice 16",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 60,
            "content": "def calculate_fibonacci(n):\n    if n <= 1:\n        return n\n    return calculate_fibonacci(n-1) + calculate_fibonacci(n-2)",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Python."
        },
        {
            "id": "code_py_17",
            "specialty": "Python",
            "tier": "INTERMEDIATE",
            "title": "Python Practice 17",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 56,
            "content": "def calculate_fibonacci(n):\n    if n <= 1:\n        return n\n    return calculate_fibonacci(n-1) + calculate_fibonacci(n-2)",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Python."
        },
        {
            "id": "code_py_18",
            "specialty": "Python",
            "tier": "CORE",
            "title": "Python Practice 18",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 53,
            "content": "import pandas as pd\n\ndf = pd.read_csv('data.csv')\nfiltered_df = df[df['age'] > 30]\nprint(filtered_df.describe())",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Python."
        },
        {
            "id": "code_py_19",
            "specialty": "Python",
            "tier": "CORE",
            "title": "Python Practice 19",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 56,
            "content": "class Animal:\n    def __init__(self, name):\n        self.name = name\n\n    def speak(self):\n        pass",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Python."
        },
        {
            "id": "code_py_20",
            "specialty": "Python",
            "tier": "CORE",
            "title": "Python Practice 20",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 68,
            "content": "class Animal:\n    def __init__(self, name):\n        self.name = name\n\n    def speak(self):\n        pass",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Python."
        }
    ],
    "react": [
        {
            "id": "code_react_1",
            "specialty": "React",
            "tier": "INTERMEDIATE",
            "title": "React Practice 1",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 59,
            "content": "useEffect(() => {\n  const timer = setInterval(() => setTime(new Date()), 1000);\n  return () => clearInterval(timer);\n}, []);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for React."
        },
        {
            "id": "code_react_2",
            "specialty": "React",
            "tier": "CORE",
            "title": "React Practice 2",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 69,
            "content": "const UserProfile = ({ user }) => (\n  <div className=\"card\">\n    <h2>{user.name}</h2>\n    <p>{user.email}</p>\n  </div>\n);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for React."
        },
        {
            "id": "code_react_3",
            "specialty": "React",
            "tier": "INTERMEDIATE",
            "title": "React Practice 3",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 65,
            "content": "import React, { useState, useEffect } from 'react';\n\nexport const Counter = () => {\n  const [count, setCount] = useState(0);\n  return <button onClick={() => setCount(c => c + 1)}>{count}</button>;\n};",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for React."
        },
        {
            "id": "code_react_4",
            "specialty": "React",
            "tier": "CORE",
            "title": "React Practice 4",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 53,
            "content": "const UserProfile = ({ user }) => (\n  <div className=\"card\">\n    <h2>{user.name}</h2>\n    <p>{user.email}</p>\n  </div>\n);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for React."
        },
        {
            "id": "code_react_5",
            "specialty": "React",
            "tier": "INTERMEDIATE",
            "title": "React Practice 5",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 54,
            "content": "useEffect(() => {\n  const timer = setInterval(() => setTime(new Date()), 1000);\n  return () => clearInterval(timer);\n}, []);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for React."
        },
        {
            "id": "code_react_6",
            "specialty": "React",
            "tier": "INTERMEDIATE",
            "title": "React Practice 6",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 56,
            "content": "import React, { useState, useEffect } from 'react';\n\nexport const Counter = () => {\n  const [count, setCount] = useState(0);\n  return <button onClick={() => setCount(c => c + 1)}>{count}</button>;\n};",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for React."
        },
        {
            "id": "code_react_7",
            "specialty": "React",
            "tier": "CORE",
            "title": "React Practice 7",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 62,
            "content": "const UserProfile = ({ user }) => (\n  <div className=\"card\">\n    <h2>{user.name}</h2>\n    <p>{user.email}</p>\n  </div>\n);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for React."
        },
        {
            "id": "code_react_8",
            "specialty": "React",
            "tier": "CORE",
            "title": "React Practice 8",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 54,
            "content": "const UserProfile = ({ user }) => (\n  <div className=\"card\">\n    <h2>{user.name}</h2>\n    <p>{user.email}</p>\n  </div>\n);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for React."
        },
        {
            "id": "code_react_9",
            "specialty": "React",
            "tier": "CORE",
            "title": "React Practice 9",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 54,
            "content": "useEffect(() => {\n  const timer = setInterval(() => setTime(new Date()), 1000);\n  return () => clearInterval(timer);\n}, []);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for React."
        },
        {
            "id": "code_react_10",
            "specialty": "React",
            "tier": "INTERMEDIATE",
            "title": "React Practice 10",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 63,
            "content": "const UserProfile = ({ user }) => (\n  <div className=\"card\">\n    <h2>{user.name}</h2>\n    <p>{user.email}</p>\n  </div>\n);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for React."
        },
        {
            "id": "code_react_11",
            "specialty": "React",
            "tier": "CORE",
            "title": "React Practice 11",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 59,
            "content": "const UserProfile = ({ user }) => (\n  <div className=\"card\">\n    <h2>{user.name}</h2>\n    <p>{user.email}</p>\n  </div>\n);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for React."
        },
        {
            "id": "code_react_12",
            "specialty": "React",
            "tier": "CORE",
            "title": "React Practice 12",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 64,
            "content": "const UserProfile = ({ user }) => (\n  <div className=\"card\">\n    <h2>{user.name}</h2>\n    <p>{user.email}</p>\n  </div>\n);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for React."
        },
        {
            "id": "code_react_13",
            "specialty": "React",
            "tier": "CORE",
            "title": "React Practice 13",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 50,
            "content": "const UserProfile = ({ user }) => (\n  <div className=\"card\">\n    <h2>{user.name}</h2>\n    <p>{user.email}</p>\n  </div>\n);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for React."
        },
        {
            "id": "code_react_14",
            "specialty": "React",
            "tier": "CORE",
            "title": "React Practice 14",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 59,
            "content": "useEffect(() => {\n  const timer = setInterval(() => setTime(new Date()), 1000);\n  return () => clearInterval(timer);\n}, []);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for React."
        },
        {
            "id": "code_react_15",
            "specialty": "React",
            "tier": "CORE",
            "title": "React Practice 15",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 65,
            "content": "const UserProfile = ({ user }) => (\n  <div className=\"card\">\n    <h2>{user.name}</h2>\n    <p>{user.email}</p>\n  </div>\n);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for React."
        },
        {
            "id": "code_react_16",
            "specialty": "React",
            "tier": "CORE",
            "title": "React Practice 16",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 61,
            "content": "useEffect(() => {\n  const timer = setInterval(() => setTime(new Date()), 1000);\n  return () => clearInterval(timer);\n}, []);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for React."
        },
        {
            "id": "code_react_17",
            "specialty": "React",
            "tier": "CORE",
            "title": "React Practice 17",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 55,
            "content": "const UserProfile = ({ user }) => (\n  <div className=\"card\">\n    <h2>{user.name}</h2>\n    <p>{user.email}</p>\n  </div>\n);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for React."
        },
        {
            "id": "code_react_18",
            "specialty": "React",
            "tier": "CORE",
            "title": "React Practice 18",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 55,
            "content": "useEffect(() => {\n  const timer = setInterval(() => setTime(new Date()), 1000);\n  return () => clearInterval(timer);\n}, []);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for React."
        },
        {
            "id": "code_react_19",
            "specialty": "React",
            "tier": "CORE",
            "title": "React Practice 19",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 57,
            "content": "import React, { useState, useEffect } from 'react';\n\nexport const Counter = () => {\n  const [count, setCount] = useState(0);\n  return <button onClick={() => setCount(c => c + 1)}>{count}</button>;\n};",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for React."
        },
        {
            "id": "code_react_20",
            "specialty": "React",
            "tier": "INTERMEDIATE",
            "title": "React Practice 20",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 61,
            "content": "import React, { useState, useEffect } from 'react';\n\nexport const Counter = () => {\n  const [count, setCount] = useState(0);\n  return <button onClick={() => setCount(c => c + 1)}>{count}</button>;\n};",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for React."
        }
    ],
    "rust": [
        {
            "id": "code_rs_1",
            "specialty": "Rust",
            "tier": "INTERMEDIATE",
            "title": "Rust Practice 1",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 66,
            "content": "use std::collections::HashMap;\n\nlet mut scores = HashMap::new();\nscores.insert(String::from(\"Blue\"), 10);\nscores.insert(String::from(\"Yellow\"), 5);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Rust."
        },
        {
            "id": "code_rs_2",
            "specialty": "Rust",
            "tier": "CORE",
            "title": "Rust Practice 2",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 64,
            "content": "pub struct Rectangle {\n    width: u32,\n    height: u32,\n}\n\nimpl Rectangle {\n    fn area(&self) -> u32 {\n        self.width * self.height\n    }\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Rust."
        },
        {
            "id": "code_rs_3",
            "specialty": "Rust",
            "tier": "INTERMEDIATE",
            "title": "Rust Practice 3",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 60,
            "content": "pub struct Rectangle {\n    width: u32,\n    height: u32,\n}\n\nimpl Rectangle {\n    fn area(&self) -> u32 {\n        self.width * self.height\n    }\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Rust."
        },
        {
            "id": "code_rs_4",
            "specialty": "Rust",
            "tier": "INTERMEDIATE",
            "title": "Rust Practice 4",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 63,
            "content": "pub struct Rectangle {\n    width: u32,\n    height: u32,\n}\n\nimpl Rectangle {\n    fn area(&self) -> u32 {\n        self.width * self.height\n    }\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Rust."
        },
        {
            "id": "code_rs_5",
            "specialty": "Rust",
            "tier": "CORE",
            "title": "Rust Practice 5",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 58,
            "content": "use std::collections::HashMap;\n\nlet mut scores = HashMap::new();\nscores.insert(String::from(\"Blue\"), 10);\nscores.insert(String::from(\"Yellow\"), 5);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Rust."
        },
        {
            "id": "code_rs_6",
            "specialty": "Rust",
            "tier": "INTERMEDIATE",
            "title": "Rust Practice 6",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 64,
            "content": "pub struct Rectangle {\n    width: u32,\n    height: u32,\n}\n\nimpl Rectangle {\n    fn area(&self) -> u32 {\n        self.width * self.height\n    }\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Rust."
        },
        {
            "id": "code_rs_7",
            "specialty": "Rust",
            "tier": "INTERMEDIATE",
            "title": "Rust Practice 7",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 69,
            "content": "pub struct Rectangle {\n    width: u32,\n    height: u32,\n}\n\nimpl Rectangle {\n    fn area(&self) -> u32 {\n        self.width * self.height\n    }\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Rust."
        },
        {
            "id": "code_rs_8",
            "specialty": "Rust",
            "tier": "CORE",
            "title": "Rust Practice 8",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 52,
            "content": "use std::collections::HashMap;\n\nlet mut scores = HashMap::new();\nscores.insert(String::from(\"Blue\"), 10);\nscores.insert(String::from(\"Yellow\"), 5);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Rust."
        },
        {
            "id": "code_rs_9",
            "specialty": "Rust",
            "tier": "CORE",
            "title": "Rust Practice 9",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 58,
            "content": "pub struct Rectangle {\n    width: u32,\n    height: u32,\n}\n\nimpl Rectangle {\n    fn area(&self) -> u32 {\n        self.width * self.height\n    }\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Rust."
        },
        {
            "id": "code_rs_10",
            "specialty": "Rust",
            "tier": "INTERMEDIATE",
            "title": "Rust Practice 10",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 68,
            "content": "use std::collections::HashMap;\n\nlet mut scores = HashMap::new();\nscores.insert(String::from(\"Blue\"), 10);\nscores.insert(String::from(\"Yellow\"), 5);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Rust."
        },
        {
            "id": "code_rs_11",
            "specialty": "Rust",
            "tier": "CORE",
            "title": "Rust Practice 11",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 54,
            "content": "use std::collections::HashMap;\n\nlet mut scores = HashMap::new();\nscores.insert(String::from(\"Blue\"), 10);\nscores.insert(String::from(\"Yellow\"), 5);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Rust."
        },
        {
            "id": "code_rs_12",
            "specialty": "Rust",
            "tier": "CORE",
            "title": "Rust Practice 12",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 50,
            "content": "use std::collections::HashMap;\n\nlet mut scores = HashMap::new();\nscores.insert(String::from(\"Blue\"), 10);\nscores.insert(String::from(\"Yellow\"), 5);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Rust."
        },
        {
            "id": "code_rs_13",
            "specialty": "Rust",
            "tier": "INTERMEDIATE",
            "title": "Rust Practice 13",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 63,
            "content": "pub struct Rectangle {\n    width: u32,\n    height: u32,\n}\n\nimpl Rectangle {\n    fn area(&self) -> u32 {\n        self.width * self.height\n    }\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Rust."
        },
        {
            "id": "code_rs_14",
            "specialty": "Rust",
            "tier": "CORE",
            "title": "Rust Practice 14",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 66,
            "content": "fn main() {\n    let mut vec = Vec::new();\n    vec.push(1);\n    vec.push(2);\n    for x in &vec {\n        println!(\"{}\", x);\n    }\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Rust."
        },
        {
            "id": "code_rs_15",
            "specialty": "Rust",
            "tier": "CORE",
            "title": "Rust Practice 15",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 66,
            "content": "pub struct Rectangle {\n    width: u32,\n    height: u32,\n}\n\nimpl Rectangle {\n    fn area(&self) -> u32 {\n        self.width * self.height\n    }\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Rust."
        },
        {
            "id": "code_rs_16",
            "specialty": "Rust",
            "tier": "CORE",
            "title": "Rust Practice 16",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 53,
            "content": "fn main() {\n    let mut vec = Vec::new();\n    vec.push(1);\n    vec.push(2);\n    for x in &vec {\n        println!(\"{}\", x);\n    }\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Rust."
        },
        {
            "id": "code_rs_17",
            "specialty": "Rust",
            "tier": "CORE",
            "title": "Rust Practice 17",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 62,
            "content": "use std::collections::HashMap;\n\nlet mut scores = HashMap::new();\nscores.insert(String::from(\"Blue\"), 10);\nscores.insert(String::from(\"Yellow\"), 5);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Rust."
        },
        {
            "id": "code_rs_18",
            "specialty": "Rust",
            "tier": "INTERMEDIATE",
            "title": "Rust Practice 18",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 52,
            "content": "use std::collections::HashMap;\n\nlet mut scores = HashMap::new();\nscores.insert(String::from(\"Blue\"), 10);\nscores.insert(String::from(\"Yellow\"), 5);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Rust."
        },
        {
            "id": "code_rs_19",
            "specialty": "Rust",
            "tier": "CORE",
            "title": "Rust Practice 19",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 53,
            "content": "pub struct Rectangle {\n    width: u32,\n    height: u32,\n}\n\nimpl Rectangle {\n    fn area(&self) -> u32 {\n        self.width * self.height\n    }\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Rust."
        },
        {
            "id": "code_rs_20",
            "specialty": "Rust",
            "tier": "INTERMEDIATE",
            "title": "Rust Practice 20",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 53,
            "content": "use std::collections::HashMap;\n\nlet mut scores = HashMap::new();\nscores.insert(String::from(\"Blue\"), 10);\nscores.insert(String::from(\"Yellow\"), 5);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Rust."
        }
    ],
    "go": [
        {
            "id": "code_go_1",
            "specialty": "Go",
            "tier": "INTERMEDIATE",
            "title": "Go Practice 1",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 50,
            "content": "func sum(nums ...int) int {\n    total := 0\n    for _, num := range nums {\n        total += num\n    }\n    return total\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Go."
        },
        {
            "id": "code_go_2",
            "specialty": "Go",
            "tier": "CORE",
            "title": "Go Practice 2",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 68,
            "content": "type Person struct {\n    Name string\n    Age  int\n}\n\nfunc (p Person) Greet() string {\n    return \"Hi, I'm \" + p.Name\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Go."
        },
        {
            "id": "code_go_3",
            "specialty": "Go",
            "tier": "INTERMEDIATE",
            "title": "Go Practice 3",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 58,
            "content": "func sum(nums ...int) int {\n    total := 0\n    for _, num := range nums {\n        total += num\n    }\n    return total\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Go."
        },
        {
            "id": "code_go_4",
            "specialty": "Go",
            "tier": "CORE",
            "title": "Go Practice 4",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 57,
            "content": "package main\n\nimport \"fmt\"\n\nfunc main() {\n    fmt.Println(\"Hello, World!\")\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Go."
        },
        {
            "id": "code_go_5",
            "specialty": "Go",
            "tier": "INTERMEDIATE",
            "title": "Go Practice 5",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 58,
            "content": "package main\n\nimport \"fmt\"\n\nfunc main() {\n    fmt.Println(\"Hello, World!\")\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Go."
        },
        {
            "id": "code_go_6",
            "specialty": "Go",
            "tier": "CORE",
            "title": "Go Practice 6",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 69,
            "content": "type Person struct {\n    Name string\n    Age  int\n}\n\nfunc (p Person) Greet() string {\n    return \"Hi, I'm \" + p.Name\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Go."
        },
        {
            "id": "code_go_7",
            "specialty": "Go",
            "tier": "INTERMEDIATE",
            "title": "Go Practice 7",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 61,
            "content": "func sum(nums ...int) int {\n    total := 0\n    for _, num := range nums {\n        total += num\n    }\n    return total\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Go."
        },
        {
            "id": "code_go_8",
            "specialty": "Go",
            "tier": "INTERMEDIATE",
            "title": "Go Practice 8",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 55,
            "content": "func sum(nums ...int) int {\n    total := 0\n    for _, num := range nums {\n        total += num\n    }\n    return total\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Go."
        },
        {
            "id": "code_go_9",
            "specialty": "Go",
            "tier": "CORE",
            "title": "Go Practice 9",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 50,
            "content": "package main\n\nimport \"fmt\"\n\nfunc main() {\n    fmt.Println(\"Hello, World!\")\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Go."
        },
        {
            "id": "code_go_10",
            "specialty": "Go",
            "tier": "CORE",
            "title": "Go Practice 10",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 54,
            "content": "func sum(nums ...int) int {\n    total := 0\n    for _, num := range nums {\n        total += num\n    }\n    return total\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Go."
        },
        {
            "id": "code_go_11",
            "specialty": "Go",
            "tier": "CORE",
            "title": "Go Practice 11",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 63,
            "content": "type Person struct {\n    Name string\n    Age  int\n}\n\nfunc (p Person) Greet() string {\n    return \"Hi, I'm \" + p.Name\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Go."
        },
        {
            "id": "code_go_12",
            "specialty": "Go",
            "tier": "CORE",
            "title": "Go Practice 12",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 66,
            "content": "package main\n\nimport \"fmt\"\n\nfunc main() {\n    fmt.Println(\"Hello, World!\")\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Go."
        },
        {
            "id": "code_go_13",
            "specialty": "Go",
            "tier": "INTERMEDIATE",
            "title": "Go Practice 13",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 64,
            "content": "package main\n\nimport \"fmt\"\n\nfunc main() {\n    fmt.Println(\"Hello, World!\")\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Go."
        },
        {
            "id": "code_go_14",
            "specialty": "Go",
            "tier": "CORE",
            "title": "Go Practice 14",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 67,
            "content": "func sum(nums ...int) int {\n    total := 0\n    for _, num := range nums {\n        total += num\n    }\n    return total\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Go."
        },
        {
            "id": "code_go_15",
            "specialty": "Go",
            "tier": "INTERMEDIATE",
            "title": "Go Practice 15",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 67,
            "content": "package main\n\nimport \"fmt\"\n\nfunc main() {\n    fmt.Println(\"Hello, World!\")\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Go."
        },
        {
            "id": "code_go_16",
            "specialty": "Go",
            "tier": "CORE",
            "title": "Go Practice 16",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 61,
            "content": "package main\n\nimport \"fmt\"\n\nfunc main() {\n    fmt.Println(\"Hello, World!\")\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Go."
        },
        {
            "id": "code_go_17",
            "specialty": "Go",
            "tier": "CORE",
            "title": "Go Practice 17",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 59,
            "content": "type Person struct {\n    Name string\n    Age  int\n}\n\nfunc (p Person) Greet() string {\n    return \"Hi, I'm \" + p.Name\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Go."
        },
        {
            "id": "code_go_18",
            "specialty": "Go",
            "tier": "INTERMEDIATE",
            "title": "Go Practice 18",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 65,
            "content": "type Person struct {\n    Name string\n    Age  int\n}\n\nfunc (p Person) Greet() string {\n    return \"Hi, I'm \" + p.Name\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Go."
        },
        {
            "id": "code_go_19",
            "specialty": "Go",
            "tier": "INTERMEDIATE",
            "title": "Go Practice 19",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 63,
            "content": "type Person struct {\n    Name string\n    Age  int\n}\n\nfunc (p Person) Greet() string {\n    return \"Hi, I'm \" + p.Name\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Go."
        },
        {
            "id": "code_go_20",
            "specialty": "Go",
            "tier": "INTERMEDIATE",
            "title": "Go Practice 20",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 59,
            "content": "package main\n\nimport \"fmt\"\n\nfunc main() {\n    fmt.Println(\"Hello, World!\")\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for Go."
        }
    ],
    "cpp": [
        {
            "id": "code_cpp_1",
            "specialty": "C++",
            "tier": "CORE",
            "title": "C++ Practice 1",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 67,
            "content": "#include <iostream>\n#include <vector>\n\nint main() {\n    std::vector<int> numbers = {1, 2, 3, 4, 5};\n    for(int n : numbers) {\n        std::cout << n << '\\n';\n    }\n    return 0;\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for C++."
        },
        {
            "id": "code_cpp_2",
            "specialty": "C++",
            "tier": "CORE",
            "title": "C++ Practice 2",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 59,
            "content": "#include <iostream>\n#include <vector>\n\nint main() {\n    std::vector<int> numbers = {1, 2, 3, 4, 5};\n    for(int n : numbers) {\n        std::cout << n << '\\n';\n    }\n    return 0;\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for C++."
        },
        {
            "id": "code_cpp_3",
            "specialty": "C++",
            "tier": "INTERMEDIATE",
            "title": "C++ Practice 3",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 63,
            "content": "#include <iostream>\n#include <vector>\n\nint main() {\n    std::vector<int> numbers = {1, 2, 3, 4, 5};\n    for(int n : numbers) {\n        std::cout << n << '\\n';\n    }\n    return 0;\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for C++."
        },
        {
            "id": "code_cpp_4",
            "specialty": "C++",
            "tier": "INTERMEDIATE",
            "title": "C++ Practice 4",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 56,
            "content": "class MyClass {\npublic:\n    MyClass() { std::cout << \"Constructed\"; }\n    ~MyClass() { std::cout << \"Destructed\"; }\n};",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for C++."
        },
        {
            "id": "code_cpp_5",
            "specialty": "C++",
            "tier": "CORE",
            "title": "C++ Practice 5",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 69,
            "content": "class MyClass {\npublic:\n    MyClass() { std::cout << \"Constructed\"; }\n    ~MyClass() { std::cout << \"Destructed\"; }\n};",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for C++."
        },
        {
            "id": "code_cpp_6",
            "specialty": "C++",
            "tier": "INTERMEDIATE",
            "title": "C++ Practice 6",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 56,
            "content": "class MyClass {\npublic:\n    MyClass() { std::cout << \"Constructed\"; }\n    ~MyClass() { std::cout << \"Destructed\"; }\n};",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for C++."
        },
        {
            "id": "code_cpp_7",
            "specialty": "C++",
            "tier": "CORE",
            "title": "C++ Practice 7",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 68,
            "content": "template <typename T>\nT add(T a, T b) {\n    return a + b;\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for C++."
        },
        {
            "id": "code_cpp_8",
            "specialty": "C++",
            "tier": "CORE",
            "title": "C++ Practice 8",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 52,
            "content": "#include <iostream>\n#include <vector>\n\nint main() {\n    std::vector<int> numbers = {1, 2, 3, 4, 5};\n    for(int n : numbers) {\n        std::cout << n << '\\n';\n    }\n    return 0;\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for C++."
        },
        {
            "id": "code_cpp_9",
            "specialty": "C++",
            "tier": "INTERMEDIATE",
            "title": "C++ Practice 9",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 66,
            "content": "template <typename T>\nT add(T a, T b) {\n    return a + b;\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for C++."
        },
        {
            "id": "code_cpp_10",
            "specialty": "C++",
            "tier": "CORE",
            "title": "C++ Practice 10",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 67,
            "content": "class MyClass {\npublic:\n    MyClass() { std::cout << \"Constructed\"; }\n    ~MyClass() { std::cout << \"Destructed\"; }\n};",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for C++."
        },
        {
            "id": "code_cpp_11",
            "specialty": "C++",
            "tier": "CORE",
            "title": "C++ Practice 11",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 65,
            "content": "class MyClass {\npublic:\n    MyClass() { std::cout << \"Constructed\"; }\n    ~MyClass() { std::cout << \"Destructed\"; }\n};",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for C++."
        },
        {
            "id": "code_cpp_12",
            "specialty": "C++",
            "tier": "INTERMEDIATE",
            "title": "C++ Practice 12",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 63,
            "content": "template <typename T>\nT add(T a, T b) {\n    return a + b;\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for C++."
        },
        {
            "id": "code_cpp_13",
            "specialty": "C++",
            "tier": "CORE",
            "title": "C++ Practice 13",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 62,
            "content": "#include <iostream>\n#include <vector>\n\nint main() {\n    std::vector<int> numbers = {1, 2, 3, 4, 5};\n    for(int n : numbers) {\n        std::cout << n << '\\n';\n    }\n    return 0;\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for C++."
        },
        {
            "id": "code_cpp_14",
            "specialty": "C++",
            "tier": "INTERMEDIATE",
            "title": "C++ Practice 14",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 54,
            "content": "template <typename T>\nT add(T a, T b) {\n    return a + b;\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for C++."
        },
        {
            "id": "code_cpp_15",
            "specialty": "C++",
            "tier": "CORE",
            "title": "C++ Practice 15",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 60,
            "content": "#include <iostream>\n#include <vector>\n\nint main() {\n    std::vector<int> numbers = {1, 2, 3, 4, 5};\n    for(int n : numbers) {\n        std::cout << n << '\\n';\n    }\n    return 0;\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for C++."
        },
        {
            "id": "code_cpp_16",
            "specialty": "C++",
            "tier": "CORE",
            "title": "C++ Practice 16",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 55,
            "content": "template <typename T>\nT add(T a, T b) {\n    return a + b;\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for C++."
        },
        {
            "id": "code_cpp_17",
            "specialty": "C++",
            "tier": "INTERMEDIATE",
            "title": "C++ Practice 17",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 68,
            "content": "template <typename T>\nT add(T a, T b) {\n    return a + b;\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for C++."
        },
        {
            "id": "code_cpp_18",
            "specialty": "C++",
            "tier": "INTERMEDIATE",
            "title": "C++ Practice 18",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 56,
            "content": "#include <iostream>\n#include <vector>\n\nint main() {\n    std::vector<int> numbers = {1, 2, 3, 4, 5};\n    for(int n : numbers) {\n        std::cout << n << '\\n';\n    }\n    return 0;\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for C++."
        },
        {
            "id": "code_cpp_19",
            "specialty": "C++",
            "tier": "INTERMEDIATE",
            "title": "C++ Practice 19",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 64,
            "content": "template <typename T>\nT add(T a, T b) {\n    return a + b;\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for C++."
        },
        {
            "id": "code_cpp_20",
            "specialty": "C++",
            "tier": "CORE",
            "title": "C++ Practice 20",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 57,
            "content": "template <typename T>\nT add(T a, T b) {\n    return a + b;\n}",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for C++."
        }
    ],
    "sql": [
        {
            "id": "code_sql_1",
            "specialty": "SQL",
            "tier": "INTERMEDIATE",
            "title": "SQL Practice 1",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 67,
            "content": "UPDATE inventory\nSET stock = stock - 1\nWHERE product_id = 87120 AND stock > 0;",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for SQL."
        },
        {
            "id": "code_sql_2",
            "specialty": "SQL",
            "tier": "INTERMEDIATE",
            "title": "SQL Practice 2",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 65,
            "content": "CREATE TABLE IF NOT EXISTS employees (\n    id SERIAL PRIMARY KEY,\n    name VARCHAR(100) NOT NULL,\n    department VARCHAR(50),\n    salary NUMERIC(10, 2)\n);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for SQL."
        },
        {
            "id": "code_sql_3",
            "specialty": "SQL",
            "tier": "CORE",
            "title": "SQL Practice 3",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 61,
            "content": "UPDATE inventory\nSET stock = stock - 1\nWHERE product_id = 41525 AND stock > 0;",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for SQL."
        },
        {
            "id": "code_sql_4",
            "specialty": "SQL",
            "tier": "INTERMEDIATE",
            "title": "SQL Practice 4",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 59,
            "content": "SELECT u.id, u.name, COUNT(o.id) as order_count\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nGROUP BY u.id, u.name\nHAVING COUNT(o.id) > 5;",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for SQL."
        },
        {
            "id": "code_sql_5",
            "specialty": "SQL",
            "tier": "CORE",
            "title": "SQL Practice 5",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 66,
            "content": "CREATE TABLE IF NOT EXISTS employees (\n    id SERIAL PRIMARY KEY,\n    name VARCHAR(100) NOT NULL,\n    department VARCHAR(50),\n    salary NUMERIC(10, 2)\n);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for SQL."
        },
        {
            "id": "code_sql_6",
            "specialty": "SQL",
            "tier": "CORE",
            "title": "SQL Practice 6",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 62,
            "content": "UPDATE inventory\nSET stock = stock - 1\nWHERE product_id = 61127 AND stock > 0;",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for SQL."
        },
        {
            "id": "code_sql_7",
            "specialty": "SQL",
            "tier": "CORE",
            "title": "SQL Practice 7",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 67,
            "content": "UPDATE inventory\nSET stock = stock - 1\nWHERE product_id = 53926 AND stock > 0;",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for SQL."
        },
        {
            "id": "code_sql_8",
            "specialty": "SQL",
            "tier": "CORE",
            "title": "SQL Practice 8",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 65,
            "content": "SELECT u.id, u.name, COUNT(o.id) as order_count\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nGROUP BY u.id, u.name\nHAVING COUNT(o.id) > 5;",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for SQL."
        },
        {
            "id": "code_sql_9",
            "specialty": "SQL",
            "tier": "INTERMEDIATE",
            "title": "SQL Practice 9",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 69,
            "content": "UPDATE inventory\nSET stock = stock - 1\nWHERE product_id = 91214 AND stock > 0;",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for SQL."
        },
        {
            "id": "code_sql_10",
            "specialty": "SQL",
            "tier": "CORE",
            "title": "SQL Practice 10",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 55,
            "content": "CREATE TABLE IF NOT EXISTS employees (\n    id SERIAL PRIMARY KEY,\n    name VARCHAR(100) NOT NULL,\n    department VARCHAR(50),\n    salary NUMERIC(10, 2)\n);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for SQL."
        },
        {
            "id": "code_sql_11",
            "specialty": "SQL",
            "tier": "INTERMEDIATE",
            "title": "SQL Practice 11",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 52,
            "content": "CREATE TABLE IF NOT EXISTS employees (\n    id SERIAL PRIMARY KEY,\n    name VARCHAR(100) NOT NULL,\n    department VARCHAR(50),\n    salary NUMERIC(10, 2)\n);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for SQL."
        },
        {
            "id": "code_sql_12",
            "specialty": "SQL",
            "tier": "CORE",
            "title": "SQL Practice 12",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 60,
            "content": "CREATE TABLE IF NOT EXISTS employees (\n    id SERIAL PRIMARY KEY,\n    name VARCHAR(100) NOT NULL,\n    department VARCHAR(50),\n    salary NUMERIC(10, 2)\n);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for SQL."
        },
        {
            "id": "code_sql_13",
            "specialty": "SQL",
            "tier": "INTERMEDIATE",
            "title": "SQL Practice 13",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 60,
            "content": "CREATE TABLE IF NOT EXISTS employees (\n    id SERIAL PRIMARY KEY,\n    name VARCHAR(100) NOT NULL,\n    department VARCHAR(50),\n    salary NUMERIC(10, 2)\n);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for SQL."
        },
        {
            "id": "code_sql_14",
            "specialty": "SQL",
            "tier": "INTERMEDIATE",
            "title": "SQL Practice 14",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 62,
            "content": "SELECT u.id, u.name, COUNT(o.id) as order_count\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nGROUP BY u.id, u.name\nHAVING COUNT(o.id) > 5;",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for SQL."
        },
        {
            "id": "code_sql_15",
            "specialty": "SQL",
            "tier": "CORE",
            "title": "SQL Practice 15",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 54,
            "content": "SELECT u.id, u.name, COUNT(o.id) as order_count\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nGROUP BY u.id, u.name\nHAVING COUNT(o.id) > 5;",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for SQL."
        },
        {
            "id": "code_sql_16",
            "specialty": "SQL",
            "tier": "CORE",
            "title": "SQL Practice 16",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 63,
            "content": "CREATE TABLE IF NOT EXISTS employees (\n    id SERIAL PRIMARY KEY,\n    name VARCHAR(100) NOT NULL,\n    department VARCHAR(50),\n    salary NUMERIC(10, 2)\n);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for SQL."
        },
        {
            "id": "code_sql_17",
            "specialty": "SQL",
            "tier": "INTERMEDIATE",
            "title": "SQL Practice 17",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 62,
            "content": "SELECT u.id, u.name, COUNT(o.id) as order_count\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nGROUP BY u.id, u.name\nHAVING COUNT(o.id) > 5;",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for SQL."
        },
        {
            "id": "code_sql_18",
            "specialty": "SQL",
            "tier": "CORE",
            "title": "SQL Practice 18",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 53,
            "content": "CREATE TABLE IF NOT EXISTS employees (\n    id SERIAL PRIMARY KEY,\n    name VARCHAR(100) NOT NULL,\n    department VARCHAR(50),\n    salary NUMERIC(10, 2)\n);",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for SQL."
        },
        {
            "id": "code_sql_19",
            "specialty": "SQL",
            "tier": "INTERMEDIATE",
            "title": "SQL Practice 19",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 60,
            "content": "UPDATE inventory\nSET stock = stock - 1\nWHERE product_id = 85749 AND stock > 0;",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for SQL."
        },
        {
            "id": "code_sql_20",
            "specialty": "SQL",
            "tier": "INTERMEDIATE",
            "title": "SQL Practice 20",
            "recommendedMinutes": 5,
            "focusType": "SYNTAX",
            "speedTargetWpm": 50,
            "content": "UPDATE inventory\nSET stock = stock - 1\nWHERE product_id = 12153 AND stock > 0;",
            "difficulty": "Professional",
            "category": "Code",
            "description": "Auto-generated code track drill for SQL."
        }
    ]
};

export function getCodeDrillsBySpecialty(specialty: string): Drill[] {
    const keyMap: Record<string, string> = {
        'typescript': 'typescript',
        'python': 'python',
        'react': 'react',
        'rust': 'rust',
        'go': 'go',
        'c++': 'cpp',
        'sql': 'sql'
    };
    
    const mappedKey = keyMap[specialty.toLowerCase().replace(/\s+/g, '')] || specialty.toLowerCase();
    return codeDrillPacks[mappedKey] || [];
}

export function getRandomCodeDrill(tier?: 'CORE' | 'INTERMEDIATE' | 'SPECIALIST', specialty?: string): Drill | null {
    let pool: Drill[] = [];

    if (specialty) {
        pool = getCodeDrillsBySpecialty(specialty);
    } else {
        Object.values(codeDrillPacks).forEach(pack => pool.push(...pack));
    }

    if (tier) {
        pool = pool.filter(d => d.tier === tier);
    }

    if (pool.length === 0) return null;

    return pool[Math.floor(Math.random() * pool.length)];
}
