import { Drill } from '../drillLibrary';

// Auto-generated expanded legal drills
export const legalDrillPacks: Record<string, Drill[]> = {
    "corporate": [
        {
            "id": "legal_corp_1",
            "specialty": "Corporate",
            "tier": "INTERMEDIATE",
            "title": "Corporate Practice 1",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 83,
            "content": "Section 12.3: Confidentiality. The Receiving Party shall not disclose any Confidential Information, including but not limited to trade secrets, to any third party without prior written consent.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Corporate."
        },
        {
            "id": "legal_corp_2",
            "specialty": "Corporate",
            "tier": "INTERMEDIATE",
            "title": "Corporate Practice 2",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 78,
            "content": "Section 8.5: Confidentiality. The Receiving Party shall not disclose any Confidential Information, including but not limited to customer lists, to any third party without prior written consent.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Corporate."
        },
        {
            "id": "legal_corp_3",
            "specialty": "Corporate",
            "tier": "CORE",
            "title": "Corporate Practice 3",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 73,
            "content": "Section 501(c)(3): Confidentiality. The Receiving Party shall not disclose any Confidential Information, including but not limited to financial data, to any third party without prior written consent.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Corporate."
        },
        {
            "id": "legal_corp_4",
            "specialty": "Corporate",
            "tier": "INTERMEDIATE",
            "title": "Corporate Practice 4",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 83,
            "content": "Section 351: Confidentiality. The Receiving Party shall not disclose any Confidential Information, including but not limited to financial data, to any third party without prior written consent.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Corporate."
        },
        {
            "id": "legal_corp_5",
            "specialty": "Corporate",
            "tier": "INTERMEDIATE",
            "title": "Corporate Practice 5",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 82,
            "content": "Pursuant to the terms and conditions set forth herein, Global Industries agrees to indemnify and hold harmless Beta Inc from any and all claims arising out of the breach of this Agreement.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Corporate."
        },
        {
            "id": "legal_corp_6",
            "specialty": "Corporate",
            "tier": "CORE",
            "title": "Corporate Practice 6",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 77,
            "content": "Section 501(c)(3): Confidentiality. The Receiving Party shall not disclose any Confidential Information, including but not limited to proprietary algorithms, to any third party without prior written consent.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Corporate."
        },
        {
            "id": "legal_corp_7",
            "specialty": "Corporate",
            "tier": "INTERMEDIATE",
            "title": "Corporate Practice 7",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 83,
            "content": "This Agreement shall be governed by and construed in accordance with the laws of the State of Delaware, without giving effect to any choice or conflict of law provision.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Corporate."
        },
        {
            "id": "legal_corp_8",
            "specialty": "Corporate",
            "tier": "INTERMEDIATE",
            "title": "Corporate Practice 8",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 76,
            "content": "Pursuant to the terms and conditions set forth herein, The Assignor agrees to indemnify and hold harmless Delta Corp from any and all claims arising out of the breach of this Agreement.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Corporate."
        },
        {
            "id": "legal_corp_9",
            "specialty": "Corporate",
            "tier": "INTERMEDIATE",
            "title": "Corporate Practice 9",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 83,
            "content": "This Agreement shall be governed by and construed in accordance with the laws of the State of Delaware, without giving effect to any choice or conflict of law provision.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Corporate."
        },
        {
            "id": "legal_corp_10",
            "specialty": "Corporate",
            "tier": "INTERMEDIATE",
            "title": "Corporate Practice 10",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 77,
            "content": "This Agreement shall be governed by and construed in accordance with the laws of the State of Delaware, without giving effect to any choice or conflict of law provision.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Corporate."
        },
        {
            "id": "legal_corp_11",
            "specialty": "Corporate",
            "tier": "CORE",
            "title": "Corporate Practice 11",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 81,
            "content": "Section 351: Confidentiality. The Receiving Party shall not disclose any Confidential Information, including but not limited to source code, to any third party without prior written consent.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Corporate."
        },
        {
            "id": "legal_corp_12",
            "specialty": "Corporate",
            "tier": "INTERMEDIATE",
            "title": "Corporate Practice 12",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 73,
            "content": "Pursuant to the terms and conditions set forth herein, Tech Solutions LLC agrees to indemnify and hold harmless Mary Major from any and all claims arising out of the breach of this Agreement.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Corporate."
        },
        {
            "id": "legal_corp_13",
            "specialty": "Corporate",
            "tier": "CORE",
            "title": "Corporate Practice 13",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 88,
            "content": "This Agreement shall be governed by and construed in accordance with the laws of the State of Delaware, without giving effect to any choice or conflict of law provision.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Corporate."
        },
        {
            "id": "legal_corp_14",
            "specialty": "Corporate",
            "tier": "CORE",
            "title": "Corporate Practice 14",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 85,
            "content": "Pursuant to the terms and conditions set forth herein, Jane Smith agrees to indemnify and hold harmless Innovate LLC from any and all claims arising out of the breach of this Agreement.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Corporate."
        },
        {
            "id": "legal_corp_15",
            "specialty": "Corporate",
            "tier": "INTERMEDIATE",
            "title": "Corporate Practice 15",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 82,
            "content": "Pursuant to the terms and conditions set forth herein, Acme Corp agrees to indemnify and hold harmless Delta Corp from any and all claims arising out of the breach of this Agreement.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Corporate."
        },
        {
            "id": "legal_corp_16",
            "specialty": "Corporate",
            "tier": "INTERMEDIATE",
            "title": "Corporate Practice 16",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 87,
            "content": "Pursuant to the terms and conditions set forth herein, Acme Corp agrees to indemnify and hold harmless The Assignee from any and all claims arising out of the breach of this Agreement.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Corporate."
        },
        {
            "id": "legal_corp_17",
            "specialty": "Corporate",
            "tier": "INTERMEDIATE",
            "title": "Corporate Practice 17",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 74,
            "content": "Section 8.5: Confidentiality. The Receiving Party shall not disclose any Confidential Information, including but not limited to source code, to any third party without prior written consent.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Corporate."
        },
        {
            "id": "legal_corp_18",
            "specialty": "Corporate",
            "tier": "INTERMEDIATE",
            "title": "Corporate Practice 18",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 72,
            "content": "Pursuant to the terms and conditions set forth herein, Jane Smith agrees to indemnify and hold harmless Richard Roe from any and all claims arising out of the breach of this Agreement.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Corporate."
        },
        {
            "id": "legal_corp_19",
            "specialty": "Corporate",
            "tier": "CORE",
            "title": "Corporate Practice 19",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 84,
            "content": "This Agreement shall be governed by and construed in accordance with the laws of the State of Delaware, without giving effect to any choice or conflict of law provision.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Corporate."
        },
        {
            "id": "legal_corp_20",
            "specialty": "Corporate",
            "tier": "CORE",
            "title": "Corporate Practice 20",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 70,
            "content": "Pursuant to the terms and conditions set forth herein, Global Industries agrees to indemnify and hold harmless The Grantee from any and all claims arising out of the breach of this Agreement.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Corporate."
        }
    ],
    "criminal": [
        {
            "id": "legal_crim_1",
            "specialty": "Criminal",
            "tier": "CORE",
            "title": "Criminal Practice 1",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 77,
            "content": "Counsel for the defense objects on the grounds of hearsay. The court sustains the objection and strikes the witness's testimony regarding the alleged meeting.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Criminal."
        },
        {
            "id": "legal_crim_2",
            "specialty": "Criminal",
            "tier": "INTERMEDIATE",
            "title": "Criminal Practice 2",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 73,
            "content": "The defendant enters a plea of not guilty to the charge of grand larceny. Bail is set at $1,000,000, and the preliminary hearing is scheduled for March 1st.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Criminal."
        },
        {
            "id": "legal_crim_3",
            "specialty": "Criminal",
            "tier": "CORE",
            "title": "Criminal Practice 3",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 77,
            "content": "The defendant enters a plea of not guilty to the charge of embezzlement. Bail is set at $100,000, and the preliminary hearing is scheduled for March 1st.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Criminal."
        },
        {
            "id": "legal_crim_4",
            "specialty": "Criminal",
            "tier": "CORE",
            "title": "Criminal Practice 4",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 74,
            "content": "Counsel for the defense objects on the grounds of relevance. The court sustains the objection and strikes the witness's testimony regarding the financial transaction.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Criminal."
        },
        {
            "id": "legal_crim_5",
            "specialty": "Criminal",
            "tier": "INTERMEDIATE",
            "title": "Criminal Practice 5",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 84,
            "content": "The defendant enters a plea of not guilty to the charge of grand larceny. Bail is set at $50,000, and the preliminary hearing is scheduled for December 31, 2023.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Criminal."
        },
        {
            "id": "legal_crim_6",
            "specialty": "Criminal",
            "tier": "INTERMEDIATE",
            "title": "Criminal Practice 6",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 88,
            "content": "In the matter of United States v. Doe, the defendant is charged with insider trading. The prosecution must prove beyond a reasonable doubt all elements of the offense.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Criminal."
        },
        {
            "id": "legal_crim_7",
            "specialty": "Criminal",
            "tier": "INTERMEDIATE",
            "title": "Criminal Practice 7",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 74,
            "content": "In the matter of People v. Johnson, the defendant is charged with embezzlement. The prosecution must prove beyond a reasonable doubt all elements of the offense.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Criminal."
        },
        {
            "id": "legal_crim_8",
            "specialty": "Criminal",
            "tier": "INTERMEDIATE",
            "title": "Criminal Practice 8",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 77,
            "content": "Counsel for the defense objects on the grounds of relevance. The court sustains the objection and strikes the witness's testimony regarding the recovered documents.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Criminal."
        },
        {
            "id": "legal_crim_9",
            "specialty": "Criminal",
            "tier": "INTERMEDIATE",
            "title": "Criminal Practice 9",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 71,
            "content": "The defendant enters a plea of not guilty to the charge of grand larceny. Bail is set at $100,000, and the preliminary hearing is scheduled for the effective date.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Criminal."
        },
        {
            "id": "legal_crim_10",
            "specialty": "Criminal",
            "tier": "CORE",
            "title": "Criminal Practice 10",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 87,
            "content": "In the matter of People v. Johnson, the defendant is charged with embezzlement. The prosecution must prove beyond a reasonable doubt all elements of the offense.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Criminal."
        },
        {
            "id": "legal_crim_11",
            "specialty": "Criminal",
            "tier": "CORE",
            "title": "Criminal Practice 11",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 77,
            "content": "Counsel for the defense objects on the grounds of lack of foundation. The court sustains the objection and strikes the witness's testimony regarding the timeline of events.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Criminal."
        },
        {
            "id": "legal_crim_12",
            "specialty": "Criminal",
            "tier": "CORE",
            "title": "Criminal Practice 12",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 80,
            "content": "In the matter of State v. Smith, the defendant is charged with perjury. The prosecution must prove beyond a reasonable doubt all elements of the offense.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Criminal."
        },
        {
            "id": "legal_crim_13",
            "specialty": "Criminal",
            "tier": "CORE",
            "title": "Criminal Practice 13",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 80,
            "content": "In the matter of State v. Smith, the defendant is charged with embezzlement. The prosecution must prove beyond a reasonable doubt all elements of the offense.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Criminal."
        },
        {
            "id": "legal_crim_14",
            "specialty": "Criminal",
            "tier": "CORE",
            "title": "Criminal Practice 14",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 78,
            "content": "Counsel for the defense objects on the grounds of lack of foundation. The court sustains the objection and strikes the witness's testimony regarding the recovered documents.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Criminal."
        },
        {
            "id": "legal_crim_15",
            "specialty": "Criminal",
            "tier": "CORE",
            "title": "Criminal Practice 15",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 75,
            "content": "The defendant enters a plea of not guilty to the charge of wire fraud. Bail is set at $2,500, and the preliminary hearing is scheduled for December 31, 2023.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Criminal."
        },
        {
            "id": "legal_crim_16",
            "specialty": "Criminal",
            "tier": "CORE",
            "title": "Criminal Practice 16",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 74,
            "content": "The defendant enters a plea of not guilty to the charge of embezzlement. Bail is set at $2,500, and the preliminary hearing is scheduled for the effective date.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Criminal."
        },
        {
            "id": "legal_crim_17",
            "specialty": "Criminal",
            "tier": "CORE",
            "title": "Criminal Practice 17",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 85,
            "content": "The defendant enters a plea of not guilty to the charge of perjury. Bail is set at $50,000, and the preliminary hearing is scheduled for March 1st.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Criminal."
        },
        {
            "id": "legal_crim_18",
            "specialty": "Criminal",
            "tier": "CORE",
            "title": "Criminal Practice 18",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 81,
            "content": "Counsel for the defense objects on the grounds of leading the witness. The court sustains the objection and strikes the witness's testimony regarding the timeline of events.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Criminal."
        },
        {
            "id": "legal_crim_19",
            "specialty": "Criminal",
            "tier": "CORE",
            "title": "Criminal Practice 19",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 83,
            "content": "Counsel for the defense objects on the grounds of relevance. The court sustains the objection and strikes the witness's testimony regarding the financial transaction.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Criminal."
        },
        {
            "id": "legal_crim_20",
            "specialty": "Criminal",
            "tier": "INTERMEDIATE",
            "title": "Criminal Practice 20",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 76,
            "content": "Counsel for the defense objects on the grounds of lack of foundation. The court sustains the objection and strikes the witness's testimony regarding the recovered documents.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Criminal."
        }
    ],
    "contracts": [
        {
            "id": "legal_contract_1",
            "specialty": "Contracts",
            "tier": "INTERMEDIATE",
            "title": "Contracts Practice 1",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 77,
            "content": "In the event of a material breach by either party, the non-breaching party may terminate this Agreement upon 30 days written notice, provided the breach remains uncured.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Contracts."
        },
        {
            "id": "legal_contract_2",
            "specialty": "Contracts",
            "tier": "INTERMEDIATE",
            "title": "Contracts Practice 2",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 82,
            "content": "The parties hereto constitute independent contractors, and nothing contained in this Agreement shall be construed to create a partnership, joint venture, or agency relationship.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Contracts."
        },
        {
            "id": "legal_contract_3",
            "specialty": "Contracts",
            "tier": "CORE",
            "title": "Contracts Practice 3",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 89,
            "content": "The parties hereto constitute independent contractors, and nothing contained in this Agreement shall be construed to create a partnership, joint venture, or agency relationship.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Contracts."
        },
        {
            "id": "legal_contract_4",
            "specialty": "Contracts",
            "tier": "CORE",
            "title": "Contracts Practice 4",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 88,
            "content": "The parties hereto constitute independent contractors, and nothing contained in this Agreement shall be construed to create a partnership, joint venture, or agency relationship.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Contracts."
        },
        {
            "id": "legal_contract_5",
            "specialty": "Contracts",
            "tier": "INTERMEDIATE",
            "title": "Contracts Practice 5",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 71,
            "content": "This Non-Disclosure Agreement (the \"Agreement\") is entered into on the effective date by and between Acme Corp (\"Disclosing Party\") and The Defendant (\"Receiving Party\").",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Contracts."
        },
        {
            "id": "legal_contract_6",
            "specialty": "Contracts",
            "tier": "CORE",
            "title": "Contracts Practice 6",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 86,
            "content": "In the event of a material breach by either party, the non-breaching party may terminate this Agreement upon 90 days written notice, provided the breach remains uncured.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Contracts."
        },
        {
            "id": "legal_contract_7",
            "specialty": "Contracts",
            "tier": "INTERMEDIATE",
            "title": "Contracts Practice 7",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 70,
            "content": "The parties hereto constitute independent contractors, and nothing contained in this Agreement shall be construed to create a partnership, joint venture, or agency relationship.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Contracts."
        },
        {
            "id": "legal_contract_8",
            "specialty": "Contracts",
            "tier": "CORE",
            "title": "Contracts Practice 8",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 83,
            "content": "The parties hereto constitute independent contractors, and nothing contained in this Agreement shall be construed to create a partnership, joint venture, or agency relationship.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Contracts."
        },
        {
            "id": "legal_contract_9",
            "specialty": "Contracts",
            "tier": "CORE",
            "title": "Contracts Practice 9",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 80,
            "content": "This Non-Disclosure Agreement (the \"Agreement\") is entered into on January 15, 2024 by and between Jane Smith (\"Disclosing Party\") and Beta Inc (\"Receiving Party\").",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Contracts."
        },
        {
            "id": "legal_contract_10",
            "specialty": "Contracts",
            "tier": "INTERMEDIATE",
            "title": "Contracts Practice 10",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 79,
            "content": "The parties hereto constitute independent contractors, and nothing contained in this Agreement shall be construed to create a partnership, joint venture, or agency relationship.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Contracts."
        },
        {
            "id": "legal_contract_11",
            "specialty": "Contracts",
            "tier": "INTERMEDIATE",
            "title": "Contracts Practice 11",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 73,
            "content": "This Non-Disclosure Agreement (the \"Agreement\") is entered into on January 15, 2024 by and between Acme Corp (\"Disclosing Party\") and Mary Major (\"Receiving Party\").",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Contracts."
        },
        {
            "id": "legal_contract_12",
            "specialty": "Contracts",
            "tier": "CORE",
            "title": "Contracts Practice 12",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 87,
            "content": "This Non-Disclosure Agreement (the \"Agreement\") is entered into on October 31st by and between John Doe (\"Disclosing Party\") and The Assignee (\"Receiving Party\").",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Contracts."
        },
        {
            "id": "legal_contract_13",
            "specialty": "Contracts",
            "tier": "INTERMEDIATE",
            "title": "Contracts Practice 13",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 79,
            "content": "In the event of a material breach by either party, the non-breaching party may terminate this Agreement upon 90 days written notice, provided the breach remains uncured.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Contracts."
        },
        {
            "id": "legal_contract_14",
            "specialty": "Contracts",
            "tier": "CORE",
            "title": "Contracts Practice 14",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 80,
            "content": "This Non-Disclosure Agreement (the \"Agreement\") is entered into on the effective date by and between John Doe (\"Disclosing Party\") and The Assignee (\"Receiving Party\").",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Contracts."
        },
        {
            "id": "legal_contract_15",
            "specialty": "Contracts",
            "tier": "INTERMEDIATE",
            "title": "Contracts Practice 15",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 85,
            "content": "The parties hereto constitute independent contractors, and nothing contained in this Agreement shall be construed to create a partnership, joint venture, or agency relationship.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Contracts."
        },
        {
            "id": "legal_contract_16",
            "specialty": "Contracts",
            "tier": "CORE",
            "title": "Contracts Practice 16",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 73,
            "content": "In the event of a material breach by either party, the non-breaching party may terminate this Agreement upon 90 days written notice, provided the breach remains uncured.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Contracts."
        },
        {
            "id": "legal_contract_17",
            "specialty": "Contracts",
            "tier": "CORE",
            "title": "Contracts Practice 17",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 74,
            "content": "In the event of a material breach by either party, the non-breaching party may terminate this Agreement upon 60 days written notice, provided the breach remains uncured.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Contracts."
        },
        {
            "id": "legal_contract_18",
            "specialty": "Contracts",
            "tier": "CORE",
            "title": "Contracts Practice 18",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 78,
            "content": "The parties hereto constitute independent contractors, and nothing contained in this Agreement shall be construed to create a partnership, joint venture, or agency relationship.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Contracts."
        },
        {
            "id": "legal_contract_19",
            "specialty": "Contracts",
            "tier": "CORE",
            "title": "Contracts Practice 19",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 74,
            "content": "In the event of a material breach by either party, the non-breaching party may terminate this Agreement upon 30 days written notice, provided the breach remains uncured.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Contracts."
        },
        {
            "id": "legal_contract_20",
            "specialty": "Contracts",
            "tier": "INTERMEDIATE",
            "title": "Contracts Practice 20",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 74,
            "content": "This Non-Disclosure Agreement (the \"Agreement\") is entered into on January 15, 2024 by and between Tech Solutions LLC (\"Disclosing Party\") and Mary Major (\"Receiving Party\").",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Contracts."
        }
    ],
    "ip": [
        {
            "id": "legal_ip_1",
            "specialty": "Intellectual Property",
            "tier": "INTERMEDIATE",
            "title": "Intellectual Property Practice 1",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 81,
            "content": "Copyright infringement is alleged regarding the unauthorized reproduction and distribution of the plaintiff's original literary work, titled 'Corporate Dynamics'.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Intellectual Property."
        },
        {
            "id": "legal_ip_2",
            "specialty": "Intellectual Property",
            "tier": "INTERMEDIATE",
            "title": "Intellectual Property Practice 2",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 77,
            "content": "The trademark 'AeroDash' is actively used in commerce in connection with the sale of medical devices. The respondent's use of a confusingly similar mark constitutes trademark infringement.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Intellectual Property."
        },
        {
            "id": "legal_ip_3",
            "specialty": "Intellectual Property",
            "tier": "CORE",
            "title": "Intellectual Property Practice 3",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 84,
            "content": "Copyright infringement is alleged regarding the unauthorized reproduction and distribution of the plaintiff's original literary work, titled 'Echoes of Eternity'.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Intellectual Property."
        },
        {
            "id": "legal_ip_4",
            "specialty": "Intellectual Property",
            "tier": "CORE",
            "title": "Intellectual Property Practice 4",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 80,
            "content": "The Assignor hereby irrevocably assigns, transfers, and conveys to the Assignee all right, title, and interest in and to the Intellectual Property, including U.S. Patent No. RE45,678.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Intellectual Property."
        },
        {
            "id": "legal_ip_5",
            "specialty": "Intellectual Property",
            "tier": "INTERMEDIATE",
            "title": "Intellectual Property Practice 5",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 83,
            "content": "The Assignor hereby irrevocably assigns, transfers, and conveys to the Assignee all right, title, and interest in and to the Intellectual Property, including U.S. Patent No. 10,123,456.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Intellectual Property."
        },
        {
            "id": "legal_ip_6",
            "specialty": "Intellectual Property",
            "tier": "CORE",
            "title": "Intellectual Property Practice 6",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 83,
            "content": "The trademark 'OmniSphere' is actively used in commerce in connection with the sale of apparel. The respondent's use of a confusingly similar mark constitutes trademark infringement.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Intellectual Property."
        },
        {
            "id": "legal_ip_7",
            "specialty": "Intellectual Property",
            "tier": "CORE",
            "title": "Intellectual Property Practice 7",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 83,
            "content": "The Assignor hereby irrevocably assigns, transfers, and conveys to the Assignee all right, title, and interest in and to the Intellectual Property, including U.S. Patent No. RE45,678.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Intellectual Property."
        },
        {
            "id": "legal_ip_8",
            "specialty": "Intellectual Property",
            "tier": "INTERMEDIATE",
            "title": "Intellectual Property Practice 8",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 84,
            "content": "Copyright infringement is alleged regarding the unauthorized reproduction and distribution of the plaintiff's original literary work, titled 'Advanced Algorithms'.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Intellectual Property."
        },
        {
            "id": "legal_ip_9",
            "specialty": "Intellectual Property",
            "tier": "CORE",
            "title": "Intellectual Property Practice 9",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 70,
            "content": "The trademark 'QuantumSync' is actively used in commerce in connection with the sale of software services. The respondent's use of a confusingly similar mark constitutes trademark infringement.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Intellectual Property."
        },
        {
            "id": "legal_ip_10",
            "specialty": "Intellectual Property",
            "tier": "CORE",
            "title": "Intellectual Property Practice 10",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 83,
            "content": "The Assignor hereby irrevocably assigns, transfers, and conveys to the Assignee all right, title, and interest in and to the Intellectual Property, including U.S. Patent No. 9,876,543.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Intellectual Property."
        },
        {
            "id": "legal_ip_11",
            "specialty": "Intellectual Property",
            "tier": "CORE",
            "title": "Intellectual Property Practice 11",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 86,
            "content": "The Assignor hereby irrevocably assigns, transfers, and conveys to the Assignee all right, title, and interest in and to the Intellectual Property, including U.S. Patent No. 9,876,543.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Intellectual Property."
        },
        {
            "id": "legal_ip_12",
            "specialty": "Intellectual Property",
            "tier": "CORE",
            "title": "Intellectual Property Practice 12",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 70,
            "content": "The Assignor hereby irrevocably assigns, transfers, and conveys to the Assignee all right, title, and interest in and to the Intellectual Property, including U.S. Patent No. 10,123,456.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Intellectual Property."
        },
        {
            "id": "legal_ip_13",
            "specialty": "Intellectual Property",
            "tier": "CORE",
            "title": "Intellectual Property Practice 13",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 74,
            "content": "The Assignor hereby irrevocably assigns, transfers, and conveys to the Assignee all right, title, and interest in and to the Intellectual Property, including U.S. Patent No. 9,876,543.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Intellectual Property."
        },
        {
            "id": "legal_ip_14",
            "specialty": "Intellectual Property",
            "tier": "CORE",
            "title": "Intellectual Property Practice 14",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 85,
            "content": "Copyright infringement is alleged regarding the unauthorized reproduction and distribution of the plaintiff's original literary work, titled 'Advanced Algorithms'.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Intellectual Property."
        },
        {
            "id": "legal_ip_15",
            "specialty": "Intellectual Property",
            "tier": "CORE",
            "title": "Intellectual Property Practice 15",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 72,
            "content": "The trademark 'NovaLumina' is actively used in commerce in connection with the sale of consumer electronics. The respondent's use of a confusingly similar mark constitutes trademark infringement.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Intellectual Property."
        },
        {
            "id": "legal_ip_16",
            "specialty": "Intellectual Property",
            "tier": "INTERMEDIATE",
            "title": "Intellectual Property Practice 16",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 76,
            "content": "The trademark 'NovaLumina' is actively used in commerce in connection with the sale of medical devices. The respondent's use of a confusingly similar mark constitutes trademark infringement.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Intellectual Property."
        },
        {
            "id": "legal_ip_17",
            "specialty": "Intellectual Property",
            "tier": "CORE",
            "title": "Intellectual Property Practice 17",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 70,
            "content": "Copyright infringement is alleged regarding the unauthorized reproduction and distribution of the plaintiff's original literary work, titled 'Advanced Algorithms'.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Intellectual Property."
        },
        {
            "id": "legal_ip_18",
            "specialty": "Intellectual Property",
            "tier": "CORE",
            "title": "Intellectual Property Practice 18",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 77,
            "content": "Copyright infringement is alleged regarding the unauthorized reproduction and distribution of the plaintiff's original literary work, titled 'The Silent Horizon'.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Intellectual Property."
        },
        {
            "id": "legal_ip_19",
            "specialty": "Intellectual Property",
            "tier": "INTERMEDIATE",
            "title": "Intellectual Property Practice 19",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 89,
            "content": "Copyright infringement is alleged regarding the unauthorized reproduction and distribution of the plaintiff's original literary work, titled 'The Silent Horizon'.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Intellectual Property."
        },
        {
            "id": "legal_ip_20",
            "specialty": "Intellectual Property",
            "tier": "INTERMEDIATE",
            "title": "Intellectual Property Practice 20",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 70,
            "content": "Copyright infringement is alleged regarding the unauthorized reproduction and distribution of the plaintiff's original literary work, titled 'The Silent Horizon'.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Intellectual Property."
        }
    ],
    "litigation": [
        {
            "id": "legal_lit_1",
            "specialty": "Litigation",
            "tier": "INTERMEDIATE",
            "title": "Litigation Practice 1",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 78,
            "content": "The parties stipulate to the admissibility of the documents Bates stamped PROD_001001 to PROD_001050 for trial purposes.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Litigation."
        },
        {
            "id": "legal_lit_2",
            "specialty": "Litigation",
            "tier": "CORE",
            "title": "Litigation Practice 2",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 76,
            "content": "The parties stipulate to the admissibility of the documents Bates stamped PROD_001001 to PROD_001050 for trial purposes.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Litigation."
        },
        {
            "id": "legal_lit_3",
            "specialty": "Litigation",
            "tier": "INTERMEDIATE",
            "title": "Litigation Practice 3",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 86,
            "content": "During the deposition, the deponent testified that they had no prior knowledge of the merger negotiations. This contradicts Exhibit B entered into evidence.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Litigation."
        },
        {
            "id": "legal_lit_4",
            "specialty": "Litigation",
            "tier": "INTERMEDIATE",
            "title": "Litigation Practice 4",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 76,
            "content": "The parties stipulate to the admissibility of the documents Bates stamped PROD_001001 to PROD_001050 for trial purposes.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Litigation."
        },
        {
            "id": "legal_lit_5",
            "specialty": "Litigation",
            "tier": "CORE",
            "title": "Litigation Practice 5",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 78,
            "content": "During the deposition, the deponent testified that they had no prior knowledge of the contract signing. This contradicts Exhibit B entered into evidence.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Litigation."
        },
        {
            "id": "legal_lit_6",
            "specialty": "Litigation",
            "tier": "INTERMEDIATE",
            "title": "Litigation Practice 6",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 75,
            "content": "During the deposition, the deponent testified that they had no prior knowledge of the data breach. This contradicts Exhibit B entered into evidence.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Litigation."
        },
        {
            "id": "legal_lit_7",
            "specialty": "Litigation",
            "tier": "INTERMEDIATE",
            "title": "Litigation Practice 7",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 82,
            "content": "Plaintiff respectfully requests that the Court deny Defendant's Motion to Dismiss, as the Complaint pleads sufficient factual matter to state a claim to relief that is plausible on its face.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Litigation."
        },
        {
            "id": "legal_lit_8",
            "specialty": "Litigation",
            "tier": "INTERMEDIATE",
            "title": "Litigation Practice 8",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 80,
            "content": "The parties stipulate to the admissibility of the documents Bates stamped PROD_001001 to PROD_001050 for trial purposes.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Litigation."
        },
        {
            "id": "legal_lit_9",
            "specialty": "Litigation",
            "tier": "INTERMEDIATE",
            "title": "Litigation Practice 9",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 89,
            "content": "During the deposition, the deponent testified that they had no prior knowledge of the board meeting. This contradicts Exhibit C entered into evidence.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Litigation."
        },
        {
            "id": "legal_lit_10",
            "specialty": "Litigation",
            "tier": "CORE",
            "title": "Litigation Practice 10",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 73,
            "content": "Plaintiff respectfully requests that the Court deny Defendant's Motion to Dismiss, as the Complaint pleads sufficient factual matter to state a claim to relief that is plausible on its face.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Litigation."
        },
        {
            "id": "legal_lit_11",
            "specialty": "Litigation",
            "tier": "CORE",
            "title": "Litigation Practice 11",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 82,
            "content": "Plaintiff respectfully requests that the Court deny Defendant's Motion to Dismiss, as the Complaint pleads sufficient factual matter to state a claim to relief that is plausible on its face.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Litigation."
        },
        {
            "id": "legal_lit_12",
            "specialty": "Litigation",
            "tier": "CORE",
            "title": "Litigation Practice 12",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 77,
            "content": "The parties stipulate to the admissibility of the documents Bates stamped DEF_00001 to DEF_00500 for trial purposes.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Litigation."
        },
        {
            "id": "legal_lit_13",
            "specialty": "Litigation",
            "tier": "INTERMEDIATE",
            "title": "Litigation Practice 13",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 72,
            "content": "Plaintiff respectfully requests that the Court deny Defendant's Motion to Dismiss, as the Complaint pleads sufficient factual matter to state a claim to relief that is plausible on its face.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Litigation."
        },
        {
            "id": "legal_lit_14",
            "specialty": "Litigation",
            "tier": "INTERMEDIATE",
            "title": "Litigation Practice 14",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 75,
            "content": "Plaintiff respectfully requests that the Court deny Defendant's Motion to Dismiss, as the Complaint pleads sufficient factual matter to state a claim to relief that is plausible on its face.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Litigation."
        },
        {
            "id": "legal_lit_15",
            "specialty": "Litigation",
            "tier": "INTERMEDIATE",
            "title": "Litigation Practice 15",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 77,
            "content": "Plaintiff respectfully requests that the Court deny Defendant's Motion to Dismiss, as the Complaint pleads sufficient factual matter to state a claim to relief that is plausible on its face.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Litigation."
        },
        {
            "id": "legal_lit_16",
            "specialty": "Litigation",
            "tier": "CORE",
            "title": "Litigation Practice 16",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 81,
            "content": "Plaintiff respectfully requests that the Court deny Defendant's Motion to Dismiss, as the Complaint pleads sufficient factual matter to state a claim to relief that is plausible on its face.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Litigation."
        },
        {
            "id": "legal_lit_17",
            "specialty": "Litigation",
            "tier": "INTERMEDIATE",
            "title": "Litigation Practice 17",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 89,
            "content": "Plaintiff respectfully requests that the Court deny Defendant's Motion to Dismiss, as the Complaint pleads sufficient factual matter to state a claim to relief that is plausible on its face.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Litigation."
        },
        {
            "id": "legal_lit_18",
            "specialty": "Litigation",
            "tier": "CORE",
            "title": "Litigation Practice 18",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 82,
            "content": "Plaintiff respectfully requests that the Court deny Defendant's Motion to Dismiss, as the Complaint pleads sufficient factual matter to state a claim to relief that is plausible on its face.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Litigation."
        },
        {
            "id": "legal_lit_19",
            "specialty": "Litigation",
            "tier": "CORE",
            "title": "Litigation Practice 19",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 77,
            "content": "Plaintiff respectfully requests that the Court deny Defendant's Motion to Dismiss, as the Complaint pleads sufficient factual matter to state a claim to relief that is plausible on its face.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Litigation."
        },
        {
            "id": "legal_lit_20",
            "specialty": "Litigation",
            "tier": "CORE",
            "title": "Litigation Practice 20",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 70,
            "content": "Plaintiff respectfully requests that the Court deny Defendant's Motion to Dismiss, as the Complaint pleads sufficient factual matter to state a claim to relief that is plausible on its face.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Litigation."
        }
    ],
    "tax": [
        {
            "id": "legal_tax_1",
            "specialty": "Tax",
            "tier": "CORE",
            "title": "Tax Practice 1",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 86,
            "content": "The IRS issued a Notice of Deficiency assessing an underpayment of income tax in the amount of $100,000 for the tax year ending the effective date.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Tax."
        },
        {
            "id": "legal_tax_2",
            "specialty": "Tax",
            "tier": "CORE",
            "title": "Tax Practice 2",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 70,
            "content": "Under Section 351 of the Internal Revenue Code, the transaction qualifies as a tax-free reorganization.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Tax."
        },
        {
            "id": "legal_tax_3",
            "specialty": "Tax",
            "tier": "INTERMEDIATE",
            "title": "Tax Practice 3",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 84,
            "content": "Under Section 4.2 of the Internal Revenue Code, the transaction qualifies as a tax-free reorganization.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Tax."
        },
        {
            "id": "legal_tax_4",
            "specialty": "Tax",
            "tier": "INTERMEDIATE",
            "title": "Tax Practice 4",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 88,
            "content": "The taxpayer claims a deduction for ordinary and necessary business expenses incurred during the taxable year, pursuant to 26 U.S.C. § 162.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Tax."
        },
        {
            "id": "legal_tax_5",
            "specialty": "Tax",
            "tier": "CORE",
            "title": "Tax Practice 5",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 78,
            "content": "Under Section 1.1 of the Internal Revenue Code, the transaction qualifies as a tax-free reorganization.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Tax."
        },
        {
            "id": "legal_tax_6",
            "specialty": "Tax",
            "tier": "CORE",
            "title": "Tax Practice 6",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 82,
            "content": "Under Section 4.2 of the Internal Revenue Code, the transaction qualifies as a tax-free reorganization.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Tax."
        },
        {
            "id": "legal_tax_7",
            "specialty": "Tax",
            "tier": "CORE",
            "title": "Tax Practice 7",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 70,
            "content": "The taxpayer claims a deduction for ordinary and necessary business expenses incurred during the taxable year, pursuant to 26 U.S.C. § 162.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Tax."
        },
        {
            "id": "legal_tax_8",
            "specialty": "Tax",
            "tier": "INTERMEDIATE",
            "title": "Tax Practice 8",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 73,
            "content": "Under Section 12.3 of the Internal Revenue Code, the transaction qualifies as a tax-free reorganization.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Tax."
        },
        {
            "id": "legal_tax_9",
            "specialty": "Tax",
            "tier": "INTERMEDIATE",
            "title": "Tax Practice 9",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 84,
            "content": "Under Section 12.3 of the Internal Revenue Code, the transaction qualifies as a tax-free reorganization.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Tax."
        },
        {
            "id": "legal_tax_10",
            "specialty": "Tax",
            "tier": "INTERMEDIATE",
            "title": "Tax Practice 10",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 81,
            "content": "The IRS issued a Notice of Deficiency assessing an underpayment of income tax in the amount of $1,000,000 for the tax year ending the effective date.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Tax."
        },
        {
            "id": "legal_tax_11",
            "specialty": "Tax",
            "tier": "CORE",
            "title": "Tax Practice 11",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 70,
            "content": "Under Section 351 of the Internal Revenue Code, the transaction qualifies as a tax-free reorganization.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Tax."
        },
        {
            "id": "legal_tax_12",
            "specialty": "Tax",
            "tier": "CORE",
            "title": "Tax Practice 12",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 89,
            "content": "Under Section 8.5 of the Internal Revenue Code, the transaction qualifies as a tax-free reorganization.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Tax."
        },
        {
            "id": "legal_tax_13",
            "specialty": "Tax",
            "tier": "INTERMEDIATE",
            "title": "Tax Practice 13",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 70,
            "content": "The taxpayer claims a deduction for ordinary and necessary business expenses incurred during the taxable year, pursuant to 26 U.S.C. § 162.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Tax."
        },
        {
            "id": "legal_tax_14",
            "specialty": "Tax",
            "tier": "CORE",
            "title": "Tax Practice 14",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 85,
            "content": "The IRS issued a Notice of Deficiency assessing an underpayment of income tax in the amount of $100,000 for the tax year ending December 31, 2023.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Tax."
        },
        {
            "id": "legal_tax_15",
            "specialty": "Tax",
            "tier": "INTERMEDIATE",
            "title": "Tax Practice 15",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 70,
            "content": "The IRS issued a Notice of Deficiency assessing an underpayment of income tax in the amount of $2,500 for the tax year ending October 31st.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Tax."
        },
        {
            "id": "legal_tax_16",
            "specialty": "Tax",
            "tier": "CORE",
            "title": "Tax Practice 16",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 76,
            "content": "The taxpayer claims a deduction for ordinary and necessary business expenses incurred during the taxable year, pursuant to 26 U.S.C. § 162.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Tax."
        },
        {
            "id": "legal_tax_17",
            "specialty": "Tax",
            "tier": "CORE",
            "title": "Tax Practice 17",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 76,
            "content": "The taxpayer claims a deduction for ordinary and necessary business expenses incurred during the taxable year, pursuant to 26 U.S.C. § 162.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Tax."
        },
        {
            "id": "legal_tax_18",
            "specialty": "Tax",
            "tier": "INTERMEDIATE",
            "title": "Tax Practice 18",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 77,
            "content": "Under Section 351 of the Internal Revenue Code, the transaction qualifies as a tax-free reorganization.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Tax."
        },
        {
            "id": "legal_tax_19",
            "specialty": "Tax",
            "tier": "INTERMEDIATE",
            "title": "Tax Practice 19",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 87,
            "content": "The taxpayer claims a deduction for ordinary and necessary business expenses incurred during the taxable year, pursuant to 26 U.S.C. § 162.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Tax."
        },
        {
            "id": "legal_tax_20",
            "specialty": "Tax",
            "tier": "CORE",
            "title": "Tax Practice 20",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 83,
            "content": "Under Section 501(c)(3) of the Internal Revenue Code, the transaction qualifies as a tax-free reorganization.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Tax."
        }
    ],
    "realestate": [
        {
            "id": "legal_re_1",
            "specialty": "Real Estate",
            "tier": "CORE",
            "title": "Real Estate Practice 1",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 83,
            "content": "This Commercial Lease Agreement commences on March 1st and expires on the effective date. Tenant shall pay base rent in the amount of $5,000,000 per month.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Real Estate."
        },
        {
            "id": "legal_re_2",
            "specialty": "Real Estate",
            "tier": "INTERMEDIATE",
            "title": "Real Estate Practice 2",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 83,
            "content": "The title search revealed an encumbrance on the property in the form of a mechanic's lien filed by The Plaintiff on October 31st.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Real Estate."
        },
        {
            "id": "legal_re_3",
            "specialty": "Real Estate",
            "tier": "INTERMEDIATE",
            "title": "Real Estate Practice 3",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 71,
            "content": "This Commercial Lease Agreement commences on January 15, 2024 and expires on January 15, 2024. Tenant shall pay base rent in the amount of $1,000,000 per month.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Real Estate."
        },
        {
            "id": "legal_re_4",
            "specialty": "Real Estate",
            "tier": "INTERMEDIATE",
            "title": "Real Estate Practice 4",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 89,
            "content": "The title search revealed an encumbrance on the property in the form of a mechanic's lien filed by Tech Solutions LLC on December 31, 2023.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Real Estate."
        },
        {
            "id": "legal_re_5",
            "specialty": "Real Estate",
            "tier": "CORE",
            "title": "Real Estate Practice 5",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 80,
            "content": "This Commercial Lease Agreement commences on January 15, 2024 and expires on March 1st. Tenant shall pay base rent in the amount of $100,000 per month.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Real Estate."
        },
        {
            "id": "legal_re_6",
            "specialty": "Real Estate",
            "tier": "CORE",
            "title": "Real Estate Practice 6",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 80,
            "content": "The Grantor conveys and warrants to the Grantee, their heirs and assigns forever, the real estate described as Lot 42 in the Whispering Pines Subdivision, subject to all easements and restrictions of record.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Real Estate."
        },
        {
            "id": "legal_re_7",
            "specialty": "Real Estate",
            "tier": "INTERMEDIATE",
            "title": "Real Estate Practice 7",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 80,
            "content": "The title search revealed an encumbrance on the property in the form of a mechanic's lien filed by The Plaintiff on the effective date.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Real Estate."
        },
        {
            "id": "legal_re_8",
            "specialty": "Real Estate",
            "tier": "INTERMEDIATE",
            "title": "Real Estate Practice 8",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 80,
            "content": "This Commercial Lease Agreement commences on October 31st and expires on December 31, 2023. Tenant shall pay base rent in the amount of $1,000,000 per month.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Real Estate."
        },
        {
            "id": "legal_re_9",
            "specialty": "Real Estate",
            "tier": "CORE",
            "title": "Real Estate Practice 9",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 82,
            "content": "The Grantor conveys and warrants to the Grantee, their heirs and assigns forever, the real estate described as Parcel #12345-6789 in the County Assessor's Office, subject to all easements and restrictions of record.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Real Estate."
        },
        {
            "id": "legal_re_10",
            "specialty": "Real Estate",
            "tier": "CORE",
            "title": "Real Estate Practice 10",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 77,
            "content": "The Grantor conveys and warrants to the Grantee, their heirs and assigns forever, the real estate described as Parcel #12345-6789 in the County Assessor's Office, subject to all easements and restrictions of record.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Real Estate."
        },
        {
            "id": "legal_re_11",
            "specialty": "Real Estate",
            "tier": "CORE",
            "title": "Real Estate Practice 11",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 75,
            "content": "The Grantor conveys and warrants to the Grantee, their heirs and assigns forever, the real estate described as the premises located at 123 Main Street, subject to all easements and restrictions of record.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Real Estate."
        },
        {
            "id": "legal_re_12",
            "specialty": "Real Estate",
            "tier": "CORE",
            "title": "Real Estate Practice 12",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 78,
            "content": "The title search revealed an encumbrance on the property in the form of a mechanic's lien filed by The Grantor on December 31, 2023.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Real Estate."
        },
        {
            "id": "legal_re_13",
            "specialty": "Real Estate",
            "tier": "CORE",
            "title": "Real Estate Practice 13",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 74,
            "content": "This Commercial Lease Agreement commences on December 31, 2023 and expires on January 15, 2024. Tenant shall pay base rent in the amount of $2,500 per month.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Real Estate."
        },
        {
            "id": "legal_re_14",
            "specialty": "Real Estate",
            "tier": "CORE",
            "title": "Real Estate Practice 14",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 87,
            "content": "The title search revealed an encumbrance on the property in the form of a mechanic's lien filed by John Doe on the effective date.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Real Estate."
        },
        {
            "id": "legal_re_15",
            "specialty": "Real Estate",
            "tier": "INTERMEDIATE",
            "title": "Real Estate Practice 15",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 89,
            "content": "The Grantor conveys and warrants to the Grantee, their heirs and assigns forever, the real estate described as Lot 42 in the Whispering Pines Subdivision, subject to all easements and restrictions of record.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Real Estate."
        },
        {
            "id": "legal_re_16",
            "specialty": "Real Estate",
            "tier": "CORE",
            "title": "Real Estate Practice 16",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 80,
            "content": "The title search revealed an encumbrance on the property in the form of a mechanic's lien filed by Acme Corp on March 1st.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Real Estate."
        },
        {
            "id": "legal_re_17",
            "specialty": "Real Estate",
            "tier": "INTERMEDIATE",
            "title": "Real Estate Practice 17",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 77,
            "content": "The Grantor conveys and warrants to the Grantee, their heirs and assigns forever, the real estate described as Parcel #12345-6789 in the County Assessor's Office, subject to all easements and restrictions of record.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Real Estate."
        },
        {
            "id": "legal_re_18",
            "specialty": "Real Estate",
            "tier": "INTERMEDIATE",
            "title": "Real Estate Practice 18",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 89,
            "content": "The title search revealed an encumbrance on the property in the form of a mechanic's lien filed by John Doe on December 31, 2023.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Real Estate."
        },
        {
            "id": "legal_re_19",
            "specialty": "Real Estate",
            "tier": "INTERMEDIATE",
            "title": "Real Estate Practice 19",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 75,
            "content": "This Commercial Lease Agreement commences on October 31st and expires on December 31, 2023. Tenant shall pay base rent in the amount of $5,000,000 per month.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Real Estate."
        },
        {
            "id": "legal_re_20",
            "specialty": "Real Estate",
            "tier": "INTERMEDIATE",
            "title": "Real Estate Practice 20",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 88,
            "content": "The title search revealed an encumbrance on the property in the form of a mechanic's lien filed by The Grantor on the effective date.",
            "difficulty": "Professional",
            "category": "Legal",
            "description": "Auto-generated legal track drill for Real Estate."
        }
    ]
};

export function getLegalDrillsBySpecialty(specialty: string): Drill[] {
    const keyMap: Record<string, string> = {
        'corporate': 'corporate',
        'criminal': 'criminal',
        'contracts': 'contracts',
        'ip': 'ip',
        'litigation': 'litigation',
        'tax': 'tax',
        'realestate': 'realestate'
    };
    
    const mappedKey = keyMap[specialty.toLowerCase().replace(/\s+/g, '')] || specialty.toLowerCase();
    return legalDrillPacks[mappedKey] || [];
}

export function getRandomLegalDrill(tier?: 'CORE' | 'INTERMEDIATE' | 'SPECIALIST', specialty?: string): Drill | null {
    let pool: Drill[] = [];

    if (specialty) {
        pool = getLegalDrillsBySpecialty(specialty);
    } else {
        Object.values(legalDrillPacks).forEach(pack => pool.push(...pack));
    }

    if (tier) {
        pool = pool.filter(d => d.tier === tier);
    }

    if (pool.length === 0) return null;

    return pool[Math.floor(Math.random() * pool.length)];
}
