import { Drill } from '../drillLibrary';

// Auto-generated expanded medical drills
export const medicalDrillPacks: Record<string, Drill[]> = {
    "emergency": [
        {
            "id": "med_em_1",
            "specialty": "Emergency",
            "tier": "INTERMEDIATE",
            "title": "Emergency Practice 1",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 73,
            "content": "Patient brought in by EMS for abdominal pain. History of chronic kidney disease. EKG shows atrial fibrillation with RVR. Consult cardiology. Discharged to SNF.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Emergency."
        },
        {
            "id": "med_em_2",
            "specialty": "Emergency",
            "tier": "CORE",
            "title": "Emergency Practice 2",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 81,
            "content": "Chief complaint of palpitations starting 3 days ago. Pain is 10/10 and sharp. murmur heard at right sternal border. Labs pending. Continue current management.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Emergency."
        },
        {
            "id": "med_em_3",
            "specialty": "Emergency",
            "tier": "INTERMEDIATE",
            "title": "Emergency Practice 3",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 67,
            "content": "Patient presents to the ED with high fever and chills. Vitals are hypertensive at 180/100. Exam reveals wheezing bilaterally. Consult cardiology. Transferred to tertiary center.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Emergency."
        },
        {
            "id": "med_em_4",
            "specialty": "Emergency",
            "tier": "INTERMEDIATE",
            "title": "Emergency Practice 4",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 69,
            "content": "Patient presents to the ED with persistent vomiting. Vitals are hypertensive at 180/100. Exam reveals clear to auscultation. Increase furosemide dose. Admitted to floor.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Emergency."
        },
        {
            "id": "med_em_5",
            "specialty": "Emergency",
            "tier": "CORE",
            "title": "Emergency Practice 5",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 75,
            "content": "Patient brought in by EMS for severe shortness of breath. History of coronary artery disease. EKG shows ST elevation in inferior leads. Discharge with strict return precautions. Discharged to SNF.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Emergency."
        },
        {
            "id": "med_em_6",
            "specialty": "Emergency",
            "tier": "INTERMEDIATE",
            "title": "Emergency Practice 6",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 70,
            "content": "Chief complaint of dizziness starting 12 hours ago. Pain is cramping. diffuse tenderness to palpation. Labs pending. Continue current management.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Emergency."
        },
        {
            "id": "med_em_7",
            "specialty": "Emergency",
            "tier": "CORE",
            "title": "Emergency Practice 7",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 68,
            "content": "Patient presents to the ED with high fever and chills. Vitals are within normal limits. Exam reveals murmur heard at right sternal border. Schedule outpatient follow-up. Transferred to tertiary center.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Emergency."
        },
        {
            "id": "med_em_8",
            "specialty": "Emergency",
            "tier": "INTERMEDIATE",
            "title": "Emergency Practice 8",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 68,
            "content": "Trauma activation for motor vehicle collision. Primary survey intact. murmur heard at right sternal border. Imaging shows {imaging}. Continue current management.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Emergency."
        },
        {
            "id": "med_em_9",
            "specialty": "Emergency",
            "tier": "CORE",
            "title": "Emergency Practice 9",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 68,
            "content": "Patient presents to the ED with left-sided weakness. Vitals are tachypneic. Exam reveals clear to auscultation. Discharge with strict return precautions. Admitted to ICU.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Emergency."
        },
        {
            "id": "med_em_10",
            "specialty": "Emergency",
            "tier": "INTERMEDIATE",
            "title": "Emergency Practice 10",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 81,
            "content": "Trauma activation for pedestrian struck. Primary survey intact. no focal deficits. Imaging shows {imaging}. Schedule outpatient follow-up.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Emergency."
        },
        {
            "id": "med_em_11",
            "specialty": "Emergency",
            "tier": "CORE",
            "title": "Emergency Practice 11",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 66,
            "content": "Patient presents to the ED with acute chest pain. Vitals are hypertensive at 180/100. Exam reveals guarding and rebound tenderness. Discharge with strict return precautions. Discharged home.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Emergency."
        },
        {
            "id": "med_em_12",
            "specialty": "Emergency",
            "tier": "INTERMEDIATE",
            "title": "Emergency Practice 12",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 79,
            "content": "Trauma activation for penetrating injury. Primary survey intact. neurologically intact. Imaging shows {imaging}. Schedule outpatient follow-up.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Emergency."
        },
        {
            "id": "med_em_13",
            "specialty": "Emergency",
            "tier": "CORE",
            "title": "Emergency Practice 13",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 71,
            "content": "Patient presents to the ED with severe shortness of breath. Vitals are hypoxic on room air. Exam reveals wheezing bilaterally. Discharge with strict return precautions. Discharged home.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Emergency."
        },
        {
            "id": "med_em_14",
            "specialty": "Emergency",
            "tier": "CORE",
            "title": "Emergency Practice 14",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 77,
            "content": "Patient presents to the ED with persistent vomiting. Vitals are stable. Exam reveals no focal deficits. Admit to medicine. Admitted to floor.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Emergency."
        },
        {
            "id": "med_em_15",
            "specialty": "Emergency",
            "tier": "CORE",
            "title": "Emergency Practice 15",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 84,
            "content": "Trauma activation for pedestrian struck. Primary survey intact. guarding and rebound tenderness. Imaging shows {imaging}. Consult cardiology.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Emergency."
        },
        {
            "id": "med_em_16",
            "specialty": "Emergency",
            "tier": "CORE",
            "title": "Emergency Practice 16",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 73,
            "content": "Chief complaint of palpitations starting 2 hours ago. Pain is 10/10 and sharp. clear to auscultation. Labs pending. Admit to medicine.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Emergency."
        },
        {
            "id": "med_em_17",
            "specialty": "Emergency",
            "tier": "CORE",
            "title": "Emergency Practice 17",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 79,
            "content": "Patient brought in by EMS for palpitations. History of chronic kidney disease. EKG shows LBBB. Continue current management. Admitted to floor.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Emergency."
        },
        {
            "id": "med_em_18",
            "specialty": "Emergency",
            "tier": "INTERMEDIATE",
            "title": "Emergency Practice 18",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 75,
            "content": "Patient brought in by EMS for left-sided weakness. History of atrial fibrillation. EKG shows atrial fibrillation with RVR. Schedule outpatient follow-up. Discharged home.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Emergency."
        },
        {
            "id": "med_em_19",
            "specialty": "Emergency",
            "tier": "CORE",
            "title": "Emergency Practice 19",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 82,
            "content": "Chief complaint of acute chest pain starting 3 days ago. Pain is cramping. no focal deficits. Labs pending. Start IV antibiotics and fluids.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Emergency."
        },
        {
            "id": "med_em_20",
            "specialty": "Emergency",
            "tier": "INTERMEDIATE",
            "title": "Emergency Practice 20",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 73,
            "content": "Trauma activation for fall from 10 feet. Primary survey intact. no focal deficits. Imaging shows {imaging}. Admit to medicine.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Emergency."
        }
    ],
    "radiology": [
        {
            "id": "med_rad_1",
            "specialty": "Radiology",
            "tier": "CORE",
            "title": "Radiology Practice 1",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 70,
            "content": "Exam: Chest X-Ray PA/Lateral. Indication: rule out appendicitis. Findings: Patchy bibasilar opacities. Impression: Normal study.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Radiology."
        },
        {
            "id": "med_rad_2",
            "specialty": "Radiology",
            "tier": "CORE",
            "title": "Radiology Practice 2",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 84,
            "content": "MRI Brain performed without contrast. The liver appears fidgety. No evidence of {pathology}. Impression: Findings consistent with pneumonia.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Radiology."
        },
        {
            "id": "med_rad_3",
            "specialty": "Radiology",
            "tier": "CORE",
            "title": "Radiology Practice 3",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 74,
            "content": "Exam: MRI Brain. Indication: abdominal pain. Findings: Patchy bibasilar opacities. Impression: Normal study.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Radiology."
        },
        {
            "id": "med_rad_4",
            "specialty": "Radiology",
            "tier": "INTERMEDIATE",
            "title": "Radiology Practice 4",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 77,
            "content": "Comparison made to prior study from 2 years ago. Gallstones present without wall thickening. The kidneys is calm and cooperative. Impression: Findings consistent with pneumonia.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Radiology."
        },
        {
            "id": "med_rad_5",
            "specialty": "Radiology",
            "tier": "INTERMEDIATE",
            "title": "Radiology Practice 5",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 76,
            "content": "MRI Brain performed without contrast. The kidneys appears fidgety. No evidence of {pathology}. Impression: Findings consistent with pneumonia.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Radiology."
        },
        {
            "id": "med_rad_6",
            "specialty": "Radiology",
            "tier": "CORE",
            "title": "Radiology Practice 6",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 71,
            "content": "Exam: Renal Ultrasound. Indication: trauma. Findings: Mild degenerative changes. Impression: No acute pathology.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Radiology."
        },
        {
            "id": "med_rad_7",
            "specialty": "Radiology",
            "tier": "INTERMEDIATE",
            "title": "Radiology Practice 7",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 73,
            "content": "CT Head without contrast performed without contrast. The lungs appears disheveled. No evidence of {pathology}. Impression: No acute pathology.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Radiology."
        },
        {
            "id": "med_rad_8",
            "specialty": "Radiology",
            "tier": "CORE",
            "title": "Radiology Practice 8",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 77,
            "content": "Comparison made to prior study from last week. Gallstones present without wall thickening. The lungs is well-groomed but anxious. Impression: No acute pathology.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Radiology."
        },
        {
            "id": "med_rad_9",
            "specialty": "Radiology",
            "tier": "CORE",
            "title": "Radiology Practice 9",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 84,
            "content": "Comparison made to prior study from 2 years ago. Gallstones present without wall thickening. The gallbladder is fidgety. Impression: Normal study.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Radiology."
        },
        {
            "id": "med_rad_10",
            "specialty": "Radiology",
            "tier": "INTERMEDIATE",
            "title": "Radiology Practice 10",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 68,
            "content": "Comparison made to prior study from last week. Patchy bibasilar opacities. The liver is disheveled. Impression: Cholelithiasis without cholecystitis.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Radiology."
        },
        {
            "id": "med_rad_11",
            "specialty": "Radiology",
            "tier": "CORE",
            "title": "Radiology Practice 11",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 71,
            "content": "Comparison made to prior study from last week. Gallstones present without wall thickening. The lungs is disheveled. Impression: Findings consistent with pneumonia.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Radiology."
        },
        {
            "id": "med_rad_12",
            "specialty": "Radiology",
            "tier": "INTERMEDIATE",
            "title": "Radiology Practice 12",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 74,
            "content": "Exam: Renal Ultrasound. Indication: trauma. Findings: Unremarkable study. Impression: No acute pathology.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Radiology."
        },
        {
            "id": "med_rad_13",
            "specialty": "Radiology",
            "tier": "CORE",
            "title": "Radiology Practice 13",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 84,
            "content": "Comparison made to prior study from 2 years ago. Unremarkable study. The gallbladder is well-groomed but anxious. Impression: Findings consistent with pneumonia.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Radiology."
        },
        {
            "id": "med_rad_14",
            "specialty": "Radiology",
            "tier": "INTERMEDIATE",
            "title": "Radiology Practice 14",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 78,
            "content": "Exam: Renal Ultrasound. Indication: chronic cough. Findings: Mild degenerative changes. Impression: No acute pathology.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Radiology."
        },
        {
            "id": "med_rad_15",
            "specialty": "Radiology",
            "tier": "CORE",
            "title": "Radiology Practice 15",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 79,
            "content": "Comparison made to prior study from 6 months ago. Gallstones present without wall thickening. The lungs is calm and cooperative. Impression: Findings consistent with pneumonia.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Radiology."
        },
        {
            "id": "med_rad_16",
            "specialty": "Radiology",
            "tier": "INTERMEDIATE",
            "title": "Radiology Practice 16",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 83,
            "content": "CT Abdomen/Pelvis performed without contrast. The heart size appears fidgety. No evidence of {pathology}. Impression: Findings consistent with pneumonia.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Radiology."
        },
        {
            "id": "med_rad_17",
            "specialty": "Radiology",
            "tier": "CORE",
            "title": "Radiology Practice 17",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 77,
            "content": "Comparison made to prior study from 2 years ago. Gallstones present without wall thickening. The gallbladder is well-groomed but anxious. Impression: No acute pathology.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Radiology."
        },
        {
            "id": "med_rad_18",
            "specialty": "Radiology",
            "tier": "CORE",
            "title": "Radiology Practice 18",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 82,
            "content": "Exam: Renal Ultrasound. Indication: hematuria. Findings: Mild degenerative changes. Impression: Findings consistent with pneumonia.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Radiology."
        },
        {
            "id": "med_rad_19",
            "specialty": "Radiology",
            "tier": "INTERMEDIATE",
            "title": "Radiology Practice 19",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 72,
            "content": "Ultrasound Right Upper Quadrant performed without contrast. The gallbladder appears calm and cooperative. No evidence of {pathology}. Impression: Normal study.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Radiology."
        },
        {
            "id": "med_rad_20",
            "specialty": "Radiology",
            "tier": "CORE",
            "title": "Radiology Practice 20",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 84,
            "content": "MRI Brain performed without contrast. The kidneys appears calm and cooperative. No evidence of {pathology}. Impression: Findings consistent with pneumonia.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Radiology."
        }
    ],
    "cardiology": [
        {
            "id": "med_cardio_1",
            "specialty": "Cardiology",
            "tier": "CORE",
            "title": "Cardiology Practice 1",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 77,
            "content": "Consult for hematuria. Patient has history of asthma. Grade 1 diastolic dysfunction. Recommendation: Start IV antibiotics and fluids.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Cardiology."
        },
        {
            "id": "med_cardio_2",
            "specialty": "Cardiology",
            "tier": "INTERMEDIATE",
            "title": "Cardiology Practice 2",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 70,
            "content": "Echocardiogram reveals Mild LVH. Ejection fraction is 55-60%. Trace tricuspid regurgitation. Continue current management.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Cardiology."
        },
        {
            "id": "med_cardio_3",
            "specialty": "Cardiology",
            "tier": "CORE",
            "title": "Cardiology Practice 3",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 66,
            "content": "Consult for stroke symptoms. Patient has history of asthma. Dilated left atrium. Recommendation: Increase furosemide dose.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Cardiology."
        },
        {
            "id": "med_cardio_4",
            "specialty": "Cardiology",
            "tier": "CORE",
            "title": "Cardiology Practice 4",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 78,
            "content": "Consult for stroke symptoms. Patient has history of hypertension. Dilated left atrium. Recommendation: Discharge with strict return precautions.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Cardiology."
        },
        {
            "id": "med_cardio_5",
            "specialty": "Cardiology",
            "tier": "CORE",
            "title": "Cardiology Practice 5",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 66,
            "content": "Echocardiogram reveals Dilated left atrium. Ejection fraction is 30-35%. Trace tricuspid regurgitation. Schedule outpatient follow-up.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Cardiology."
        },
        {
            "id": "med_cardio_6",
            "specialty": "Cardiology",
            "tier": "CORE",
            "title": "Cardiology Practice 6",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 67,
            "content": "Consult for hematuria. Patient has history of hypertension. Grade 1 diastolic dysfunction. Recommendation: Prepare for OR.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Cardiology."
        },
        {
            "id": "med_cardio_7",
            "specialty": "Cardiology",
            "tier": "CORE",
            "title": "Cardiology Practice 7",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 66,
            "content": "Patient seen for follow-up of heart failure exacerbation. Reports right lower quadrant pain. EKG demonstrates T wave inversions. Discharge with strict return precautions. Discharged home.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Cardiology."
        },
        {
            "id": "med_cardio_8",
            "specialty": "Cardiology",
            "tier": "INTERMEDIATE",
            "title": "Cardiology Practice 8",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 77,
            "content": "Patient seen for follow-up of generalized anxiety disorder. Reports severe shortness of breath. EKG demonstrates ST elevation in inferior leads. Consult cardiology. Discharged to SNF.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Cardiology."
        },
        {
            "id": "med_cardio_9",
            "specialty": "Cardiology",
            "tier": "CORE",
            "title": "Cardiology Practice 9",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 69,
            "content": "Patient seen for follow-up of generalized anxiety disorder. Reports left-sided weakness. EKG demonstrates LBBB. Consult cardiology. Admitted to ICU.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Cardiology."
        },
        {
            "id": "med_cardio_10",
            "specialty": "Cardiology",
            "tier": "CORE",
            "title": "Cardiology Practice 10",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 73,
            "content": "Echocardiogram reveals Grade 1 diastolic dysfunction. Ejection fraction is 55-60%. Severe mitral valve prolapse. Continue current management.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Cardiology."
        },
        {
            "id": "med_cardio_11",
            "specialty": "Cardiology",
            "tier": "CORE",
            "title": "Cardiology Practice 11",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 68,
            "content": "Patient seen for follow-up of generalized anxiety disorder. Reports high fever and chills. EKG demonstrates normal sinus rhythm. Consult cardiology. Transferred to tertiary center.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Cardiology."
        },
        {
            "id": "med_cardio_12",
            "specialty": "Cardiology",
            "tier": "CORE",
            "title": "Cardiology Practice 12",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 70,
            "content": "Echocardiogram reveals No regional wall motion abnormalities. Ejection fraction is 60-65%. Trace tricuspid regurgitation. Start IV antibiotics and fluids.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Cardiology."
        },
        {
            "id": "med_cardio_13",
            "specialty": "Cardiology",
            "tier": "INTERMEDIATE",
            "title": "Cardiology Practice 13",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 65,
            "content": "Echocardiogram reveals Grade 1 diastolic dysfunction. Ejection fraction is 60-65%. Trace tricuspid regurgitation. Continue current management.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Cardiology."
        },
        {
            "id": "med_cardio_14",
            "specialty": "Cardiology",
            "tier": "CORE",
            "title": "Cardiology Practice 14",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 81,
            "content": "Echocardiogram reveals Mild LVH. Ejection fraction is 55-60%. Trace tricuspid regurgitation. Start IV antibiotics and fluids.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Cardiology."
        },
        {
            "id": "med_cardio_15",
            "specialty": "Cardiology",
            "tier": "CORE",
            "title": "Cardiology Practice 15",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 79,
            "content": "Patient seen for follow-up of DKA. Reports acute chest pain. EKG demonstrates LBBB. Increase furosemide dose. Transferred to tertiary center.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Cardiology."
        },
        {
            "id": "med_cardio_16",
            "specialty": "Cardiology",
            "tier": "INTERMEDIATE",
            "title": "Cardiology Practice 16",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 67,
            "content": "Patient seen for follow-up of heart failure exacerbation. Reports palpitations. EKG demonstrates normal sinus rhythm. Increase furosemide dose. Transferred to tertiary center.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Cardiology."
        },
        {
            "id": "med_cardio_17",
            "specialty": "Cardiology",
            "tier": "CORE",
            "title": "Cardiology Practice 17",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 75,
            "content": "Consult for trauma. Patient has history of coronary artery disease. No regional wall motion abnormalities. Recommendation: Start IV antibiotics and fluids.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Cardiology."
        },
        {
            "id": "med_cardio_18",
            "specialty": "Cardiology",
            "tier": "INTERMEDIATE",
            "title": "Cardiology Practice 18",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 71,
            "content": "Patient seen for follow-up of generalized anxiety disorder. Reports palpitations. EKG demonstrates LBBB. Continue current management. Admitted to ICU.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Cardiology."
        },
        {
            "id": "med_cardio_19",
            "specialty": "Cardiology",
            "tier": "INTERMEDIATE",
            "title": "Cardiology Practice 19",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 81,
            "content": "Echocardiogram reveals Grade 1 diastolic dysfunction. Ejection fraction is 40-45%. No aortic stenosis. Increase furosemide dose.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Cardiology."
        },
        {
            "id": "med_cardio_20",
            "specialty": "Cardiology",
            "tier": "INTERMEDIATE",
            "title": "Cardiology Practice 20",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 71,
            "content": "Echocardiogram reveals Grade 1 diastolic dysfunction. Ejection fraction is 55-60%. Severe mitral valve prolapse. Increase furosemide dose.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Cardiology."
        }
    ],
    "surgery": [
        {
            "id": "med_surg_1",
            "specialty": "Surgery",
            "tier": "INTERMEDIATE",
            "title": "Surgery Practice 1",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 81,
            "content": "Operative report. Exploratory laparotomy performed under spinal anesthesia. purulent fluid in the RLQ. No complications. Admit to medicine.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Surgery."
        },
        {
            "id": "med_surg_2",
            "specialty": "Surgery",
            "tier": "INTERMEDIATE",
            "title": "Surgery Practice 2",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 79,
            "content": "Operative report. Exploratory laparotomy performed under spinal anesthesia. inflamed appendix. No complications. Schedule outpatient follow-up.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Surgery."
        },
        {
            "id": "med_surg_3",
            "specialty": "Surgery",
            "tier": "INTERMEDIATE",
            "title": "Surgery Practice 3",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 82,
            "content": "Operative report. CABG performed under general endotracheal anesthesia. purulent fluid in the RLQ. No complications. Increase furosemide dose.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Surgery."
        },
        {
            "id": "med_surg_4",
            "specialty": "Surgery",
            "tier": "CORE",
            "title": "Surgery Practice 4",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 70,
            "content": "Preoperative diagnosis: sepsis. Postoperative diagnosis: Same. Procedure: Incision and drainage. Findings: purulent fluid in the RLQ. Start IV antibiotics and fluids.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Surgery."
        },
        {
            "id": "med_surg_5",
            "specialty": "Surgery",
            "tier": "CORE",
            "title": "Surgery Practice 5",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 82,
            "content": "Preoperative diagnosis: acute appendicitis. Postoperative diagnosis: Same. Procedure: Exploratory laparotomy. Findings: gallbladder with stones. Discharge with strict return precautions.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Surgery."
        },
        {
            "id": "med_surg_6",
            "specialty": "Surgery",
            "tier": "INTERMEDIATE",
            "title": "Surgery Practice 6",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 67,
            "content": "Preoperative diagnosis: generalized anxiety disorder. Postoperative diagnosis: Same. Procedure: Exploratory laparotomy. Findings: purulent fluid in the RLQ. Continue current management.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Surgery."
        },
        {
            "id": "med_surg_7",
            "specialty": "Surgery",
            "tier": "INTERMEDIATE",
            "title": "Surgery Practice 7",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 79,
            "content": "Preoperative diagnosis: major depressive disorder. Postoperative diagnosis: Same. Procedure: Cholecystectomy. Findings: purulent fluid in the RLQ. Start IV antibiotics and fluids.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Surgery."
        },
        {
            "id": "med_surg_8",
            "specialty": "Surgery",
            "tier": "INTERMEDIATE",
            "title": "Surgery Practice 8",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 79,
            "content": "Operative report. Incision and drainage performed under general endotracheal anesthesia. normal appearing bowel. No complications. Schedule outpatient follow-up.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Surgery."
        },
        {
            "id": "med_surg_9",
            "specialty": "Surgery",
            "tier": "INTERMEDIATE",
            "title": "Surgery Practice 9",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 81,
            "content": "The patient was prepped and draped. McBurney's incision was made. The gallbladder was freed from the liver bed was performed. Wound left open to heal by secondary intention. Discharged home.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Surgery."
        },
        {
            "id": "med_surg_10",
            "specialty": "Surgery",
            "tier": "INTERMEDIATE",
            "title": "Surgery Practice 10",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 72,
            "content": "Operative report. Laparoscopic appendectomy performed under general endotracheal anesthesia. inflamed appendix. No complications. Continue current management.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Surgery."
        },
        {
            "id": "med_surg_11",
            "specialty": "Surgery",
            "tier": "CORE",
            "title": "Surgery Practice 11",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 80,
            "content": "The patient was prepped and draped. Right subcostal incision was made. Abscess was drained and packed was performed. Skin closed with staples. Admitted to floor.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Surgery."
        },
        {
            "id": "med_surg_12",
            "specialty": "Surgery",
            "tier": "CORE",
            "title": "Surgery Practice 12",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 80,
            "content": "Preoperative diagnosis: generalized anxiety disorder. Postoperative diagnosis: Same. Procedure: Cholecystectomy. Findings: normal appearing bowel. Continue current management.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Surgery."
        },
        {
            "id": "med_surg_13",
            "specialty": "Surgery",
            "tier": "CORE",
            "title": "Surgery Practice 13",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 67,
            "content": "The patient was prepped and draped. Right subcostal incision was made. Abscess was drained and packed was performed. Skin closed with staples. Transferred to tertiary center.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Surgery."
        },
        {
            "id": "med_surg_14",
            "specialty": "Surgery",
            "tier": "CORE",
            "title": "Surgery Practice 14",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 84,
            "content": "Operative report. Cholecystectomy performed under spinal anesthesia. inflamed appendix. No complications. Schedule outpatient follow-up.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Surgery."
        },
        {
            "id": "med_surg_15",
            "specialty": "Surgery",
            "tier": "INTERMEDIATE",
            "title": "Surgery Practice 15",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 68,
            "content": "Preoperative diagnosis: community acquired pneumonia. Postoperative diagnosis: Same. Procedure: Cholecystectomy. Findings: gallbladder with stones. Start IV antibiotics and fluids.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Surgery."
        },
        {
            "id": "med_surg_16",
            "specialty": "Surgery",
            "tier": "INTERMEDIATE",
            "title": "Surgery Practice 16",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 71,
            "content": "The patient was prepped and draped. Right subcostal incision was made. The gallbladder was freed from the liver bed was performed. Wound left open to heal by secondary intention. Transferred to tertiary center.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Surgery."
        },
        {
            "id": "med_surg_17",
            "specialty": "Surgery",
            "tier": "INTERMEDIATE",
            "title": "Surgery Practice 17",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 76,
            "content": "The patient was prepped and draped. McBurney's incision was made. The gallbladder was freed from the liver bed was performed. Fascia closed with PDS. Admitted to floor.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Surgery."
        },
        {
            "id": "med_surg_18",
            "specialty": "Surgery",
            "tier": "CORE",
            "title": "Surgery Practice 18",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 82,
            "content": "Operative report. Exploratory laparotomy performed under MAC. inflamed appendix. No complications. Continue current management.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Surgery."
        },
        {
            "id": "med_surg_19",
            "specialty": "Surgery",
            "tier": "INTERMEDIATE",
            "title": "Surgery Practice 19",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 71,
            "content": "The patient was prepped and draped. Right subcostal incision was made. The appendix was bluntly dissected and removed was performed. Wound left open to heal by secondary intention. Admitted to ICU.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Surgery."
        },
        {
            "id": "med_surg_20",
            "specialty": "Surgery",
            "tier": "CORE",
            "title": "Surgery Practice 20",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 74,
            "content": "Preoperative diagnosis: major depressive disorder. Postoperative diagnosis: Same. Procedure: Laparoscopic appendectomy. Findings: normal appearing bowel. Admit to medicine.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Surgery."
        }
    ],
    "psychiatry": [
        {
            "id": "med_psych_1",
            "specialty": "Psychiatry",
            "tier": "INTERMEDIATE",
            "title": "Psychiatry Practice 1",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 79,
            "content": "Follow-up for community acquired pneumonia. Reports syncope. Sleep is poor. Appetite is fair. Admit to medicine.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Psychiatry."
        },
        {
            "id": "med_psych_2",
            "specialty": "Psychiatry",
            "tier": "INTERMEDIATE",
            "title": "Psychiatry Practice 2",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 67,
            "content": "Mental status exam: Patient is calm and cooperative. Mood is depressed, affect is constricted. Thought process circumstantial. Denies SI/HI. Continue current management.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Psychiatry."
        },
        {
            "id": "med_psych_3",
            "specialty": "Psychiatry",
            "tier": "CORE",
            "title": "Psychiatry Practice 3",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 83,
            "content": "Follow-up for major depressive disorder. Reports high fever and chills. Sleep is adequate. Appetite is good. Start IV antibiotics and fluids.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Psychiatry."
        },
        {
            "id": "med_psych_4",
            "specialty": "Psychiatry",
            "tier": "INTERMEDIATE",
            "title": "Psychiatry Practice 4",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 71,
            "content": "Follow-up for DKA. Reports palpitations. Sleep is adequate. Appetite is good. Prepare for OR.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Psychiatry."
        },
        {
            "id": "med_psych_5",
            "specialty": "Psychiatry",
            "tier": "INTERMEDIATE",
            "title": "Psychiatry Practice 5",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 68,
            "content": "Follow-up for DKA. Reports syncope. Sleep is interrupted. Appetite is decreased. Increase furosemide dose.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Psychiatry."
        },
        {
            "id": "med_psych_6",
            "specialty": "Psychiatry",
            "tier": "CORE",
            "title": "Psychiatry Practice 6",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 67,
            "content": "Mental status exam: Patient is well-groomed but anxious. Mood is anxious, affect is congruent. Thought process tangential. Denies SI/HI. Continue current management.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Psychiatry."
        },
        {
            "id": "med_psych_7",
            "specialty": "Psychiatry",
            "tier": "INTERMEDIATE",
            "title": "Psychiatry Practice 7",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 66,
            "content": "Follow-up for acute appendicitis. Reports severe shortness of breath. Sleep is improved. Appetite is good. Start IV antibiotics and fluids.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Psychiatry."
        },
        {
            "id": "med_psych_8",
            "specialty": "Psychiatry",
            "tier": "INTERMEDIATE",
            "title": "Psychiatry Practice 8",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 70,
            "content": "Follow-up for acute appendicitis. Reports right lower quadrant pain. Sleep is interrupted. Appetite is decreased. Consult cardiology.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Psychiatry."
        },
        {
            "id": "med_psych_9",
            "specialty": "Psychiatry",
            "tier": "INTERMEDIATE",
            "title": "Psychiatry Practice 9",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 80,
            "content": "Mental status exam: Patient is disheveled. Mood is irritable, affect is constricted. Thought process circumstantial. Denies SI/HI. Continue current management.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Psychiatry."
        },
        {
            "id": "med_psych_10",
            "specialty": "Psychiatry",
            "tier": "CORE",
            "title": "Psychiatry Practice 10",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 80,
            "content": "Follow-up for heart failure exacerbation. Reports syncope. Sleep is adequate. Appetite is good. Admit to medicine.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Psychiatry."
        },
        {
            "id": "med_psych_11",
            "specialty": "Psychiatry",
            "tier": "INTERMEDIATE",
            "title": "Psychiatry Practice 11",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 79,
            "content": "Follow-up for heart failure exacerbation. Reports right lower quadrant pain. Sleep is adequate. Appetite is decreased. Discharge with strict return precautions.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Psychiatry."
        },
        {
            "id": "med_psych_12",
            "specialty": "Psychiatry",
            "tier": "CORE",
            "title": "Psychiatry Practice 12",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 67,
            "content": "Mental status exam: Patient is calm and cooperative. Mood is depressed, affect is congruent. Thought process tangential. Denies SI/HI. Consult cardiology.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Psychiatry."
        },
        {
            "id": "med_psych_13",
            "specialty": "Psychiatry",
            "tier": "CORE",
            "title": "Psychiatry Practice 13",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 82,
            "content": "Follow-up for heart failure exacerbation. Reports acute chest pain. Sleep is poor. Appetite is decreased. Admit to medicine.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Psychiatry."
        },
        {
            "id": "med_psych_14",
            "specialty": "Psychiatry",
            "tier": "CORE",
            "title": "Psychiatry Practice 14",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 82,
            "content": "Follow-up for acute appendicitis. Reports persistent vomiting. Sleep is adequate. Appetite is good. Schedule outpatient follow-up.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Psychiatry."
        },
        {
            "id": "med_psych_15",
            "specialty": "Psychiatry",
            "tier": "INTERMEDIATE",
            "title": "Psychiatry Practice 15",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 65,
            "content": "Follow-up for heart failure exacerbation. Reports left-sided weakness. Sleep is adequate. Appetite is increased. Start IV antibiotics and fluids.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Psychiatry."
        },
        {
            "id": "med_psych_16",
            "specialty": "Psychiatry",
            "tier": "INTERMEDIATE",
            "title": "Psychiatry Practice 16",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 68,
            "content": "Follow-up for DKA. Reports sudden onset headache. Sleep is interrupted. Appetite is decreased. Start IV antibiotics and fluids.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Psychiatry."
        },
        {
            "id": "med_psych_17",
            "specialty": "Psychiatry",
            "tier": "CORE",
            "title": "Psychiatry Practice 17",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 79,
            "content": "Follow-up for community acquired pneumonia. Reports abdominal pain. Sleep is interrupted. Appetite is good. Discharge with strict return precautions.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Psychiatry."
        },
        {
            "id": "med_psych_18",
            "specialty": "Psychiatry",
            "tier": "INTERMEDIATE",
            "title": "Psychiatry Practice 18",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 83,
            "content": "Mental status exam: Patient is calm and cooperative. Mood is depressed, affect is congruent. Thought process linear and goal-directed. Denies SI/HI. Admit to medicine.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Psychiatry."
        },
        {
            "id": "med_psych_19",
            "specialty": "Psychiatry",
            "tier": "INTERMEDIATE",
            "title": "Psychiatry Practice 19",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 83,
            "content": "Mental status exam: Patient is well-groomed but anxious. Mood is irritable, affect is constricted. Thought process circumstantial. Denies SI/HI. Start IV antibiotics and fluids.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Psychiatry."
        },
        {
            "id": "med_psych_20",
            "specialty": "Psychiatry",
            "tier": "INTERMEDIATE",
            "title": "Psychiatry Practice 20",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 71,
            "content": "Mental status exam: Patient is calm and cooperative. Mood is euthymic, affect is congruent. Thought process circumstantial. Denies SI/HI. Continue current management.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Psychiatry."
        }
    ],
    "soap": [
        {
            "id": "med_soap_1",
            "specialty": "Internal Medicine",
            "tier": "INTERMEDIATE",
            "title": "Internal Medicine Practice 1",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 75,
            "content": "S: palpitations. O: Vitals hypertensive at 180/100. Exam: neurologically intact. A: major depressive disorder. P: Admit to medicine.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Internal Medicine."
        },
        {
            "id": "med_soap_2",
            "specialty": "Internal Medicine",
            "tier": "INTERMEDIATE",
            "title": "Internal Medicine Practice 2",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 78,
            "content": "S: Patient follows up for DKA. O: diffuse tenderness to palpation. A: major depressive disorder, worsening. P: Schedule outpatient follow-up.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Internal Medicine."
        },
        {
            "id": "med_soap_3",
            "specialty": "Internal Medicine",
            "tier": "CORE",
            "title": "Internal Medicine Practice 3",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 80,
            "content": "S: Patient follows up for acute appendicitis. O: guarding and rebound tenderness. A: community acquired pneumonia, poorly controlled. P: Continue current management.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Internal Medicine."
        },
        {
            "id": "med_soap_4",
            "specialty": "Internal Medicine",
            "tier": "INTERMEDIATE",
            "title": "Internal Medicine Practice 4",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 73,
            "content": "S: Patient follows up for DKA. O: neurologically intact. A: sepsis, stable. P: Consult cardiology.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Internal Medicine."
        },
        {
            "id": "med_soap_5",
            "specialty": "Internal Medicine",
            "tier": "INTERMEDIATE",
            "title": "Internal Medicine Practice 5",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 68,
            "content": "S: syncope. O: Vitals tachycardic and hypotensive. Exam: clear to auscultation. A: community acquired pneumonia. P: Start IV antibiotics and fluids.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Internal Medicine."
        },
        {
            "id": "med_soap_6",
            "specialty": "Internal Medicine",
            "tier": "INTERMEDIATE",
            "title": "Internal Medicine Practice 6",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 81,
            "content": "S: Patient follows up for heart failure exacerbation. O: wheezing bilaterally. A: major depressive disorder, poorly controlled. P: Admit to medicine.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Internal Medicine."
        },
        {
            "id": "med_soap_7",
            "specialty": "Internal Medicine",
            "tier": "CORE",
            "title": "Internal Medicine Practice 7",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 66,
            "content": "S: palpitations. O: Vitals febrile to 102F. Exam: guarding and rebound tenderness. A: community acquired pneumonia. P: Admit to medicine.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Internal Medicine."
        },
        {
            "id": "med_soap_8",
            "specialty": "Internal Medicine",
            "tier": "CORE",
            "title": "Internal Medicine Practice 8",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 67,
            "content": "S: Patient follows up for generalized anxiety disorder. O: guarding and rebound tenderness. A: community acquired pneumonia, improving. P: Increase furosemide dose.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Internal Medicine."
        },
        {
            "id": "med_soap_9",
            "specialty": "Internal Medicine",
            "tier": "CORE",
            "title": "Internal Medicine Practice 9",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 65,
            "content": "S: Patient follows up for major depressive disorder. O: wheezing bilaterally. A: generalized anxiety disorder, poorly controlled. P: Increase furosemide dose.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Internal Medicine."
        },
        {
            "id": "med_soap_10",
            "specialty": "Internal Medicine",
            "tier": "CORE",
            "title": "Internal Medicine Practice 10",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 71,
            "content": "S: Patient follows up for DKA. O: guarding and rebound tenderness. A: major depressive disorder, stable. P: Schedule outpatient follow-up.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Internal Medicine."
        },
        {
            "id": "med_soap_11",
            "specialty": "Internal Medicine",
            "tier": "INTERMEDIATE",
            "title": "Internal Medicine Practice 11",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 84,
            "content": "S: syncope. O: Vitals tachycardic and hypotensive. Exam: wheezing bilaterally. A: acute appendicitis. P: Increase furosemide dose.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Internal Medicine."
        },
        {
            "id": "med_soap_12",
            "specialty": "Internal Medicine",
            "tier": "INTERMEDIATE",
            "title": "Internal Medicine Practice 12",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 77,
            "content": "S: persistent vomiting. O: Vitals tachypneic. Exam: wheezing bilaterally. A: generalized anxiety disorder. P: Schedule outpatient follow-up.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Internal Medicine."
        },
        {
            "id": "med_soap_13",
            "specialty": "Internal Medicine",
            "tier": "INTERMEDIATE",
            "title": "Internal Medicine Practice 13",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 78,
            "content": "S: Patient follows up for acute appendicitis. O: neurologically intact. A: community acquired pneumonia, worsening. P: Increase furosemide dose.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Internal Medicine."
        },
        {
            "id": "med_soap_14",
            "specialty": "Internal Medicine",
            "tier": "CORE",
            "title": "Internal Medicine Practice 14",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 74,
            "content": "S: Patient follows up for acute appendicitis. O: neurologically intact. A: DKA, stable. P: Discharge with strict return precautions.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Internal Medicine."
        },
        {
            "id": "med_soap_15",
            "specialty": "Internal Medicine",
            "tier": "INTERMEDIATE",
            "title": "Internal Medicine Practice 15",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 74,
            "content": "S: Patient follows up for DKA. O: wheezing bilaterally. A: heart failure exacerbation, worsening. P: Continue current management.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Internal Medicine."
        },
        {
            "id": "med_soap_16",
            "specialty": "Internal Medicine",
            "tier": "INTERMEDIATE",
            "title": "Internal Medicine Practice 16",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 68,
            "content": "S: acute chest pain. O: Vitals hypertensive at 180/100. Exam: murmur heard at right sternal border. A: sepsis. P: Discharge with strict return precautions.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Internal Medicine."
        },
        {
            "id": "med_soap_17",
            "specialty": "Internal Medicine",
            "tier": "INTERMEDIATE",
            "title": "Internal Medicine Practice 17",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 83,
            "content": "S: Patient follows up for community acquired pneumonia. O: wheezing bilaterally. A: sepsis, stable. P: Increase furosemide dose.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Internal Medicine."
        },
        {
            "id": "med_soap_18",
            "specialty": "Internal Medicine",
            "tier": "CORE",
            "title": "Internal Medicine Practice 18",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 76,
            "content": "S: dizziness. O: Vitals hypoxic on room air. Exam: clear to auscultation. A: generalized anxiety disorder. P: Continue current management.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Internal Medicine."
        },
        {
            "id": "med_soap_19",
            "specialty": "Internal Medicine",
            "tier": "CORE",
            "title": "Internal Medicine Practice 19",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 66,
            "content": "S: acute chest pain. O: Vitals within normal limits. Exam: wheezing bilaterally. A: heart failure exacerbation. P: Discharge with strict return precautions.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Internal Medicine."
        },
        {
            "id": "med_soap_20",
            "specialty": "Internal Medicine",
            "tier": "CORE",
            "title": "Internal Medicine Practice 20",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 83,
            "content": "S: Patient follows up for community acquired pneumonia. O: wheezing bilaterally. A: community acquired pneumonia, stable. P: Admit to medicine.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Internal Medicine."
        }
    ],
    "discharge": [
        {
            "id": "med_dc_1",
            "specialty": "Hospitalist",
            "tier": "INTERMEDIATE",
            "title": "Hospitalist Practice 1",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 68,
            "content": "Admitted for DKA. Treated with IV fluids and insulin. Course was uncomplicated. Discharged to Admitted to ICU on maintenance inhalers.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Hospitalist."
        },
        {
            "id": "med_dc_2",
            "specialty": "Hospitalist",
            "tier": "CORE",
            "title": "Hospitalist Practice 2",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 74,
            "content": "Hospital course: Patient admitted with high fever and chills, found to have community acquired pneumonia. albuterol returning initiated. Condition improved. Discharge instructions: Admit to medicine.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Hospitalist."
        },
        {
            "id": "med_dc_3",
            "specialty": "Hospitalist",
            "tier": "CORE",
            "title": "Hospitalist Practice 3",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 73,
            "content": "Admitted for major depressive disorder. Treated with lisinopril and amlodipine. Course was complicated by transient AKI. Discharged to Admitted to ICU on maintenance inhalers.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Hospitalist."
        },
        {
            "id": "med_dc_4",
            "specialty": "Hospitalist",
            "tier": "INTERMEDIATE",
            "title": "Hospitalist Practice 4",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 67,
            "content": "Hospital course: Patient admitted with right lower quadrant pain, found to have community acquired pneumonia. lisinopril and amlodipine initiated. Condition improved. Discharge instructions: Discharge with strict return precautions.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Hospitalist."
        },
        {
            "id": "med_dc_5",
            "specialty": "Hospitalist",
            "tier": "INTERMEDIATE",
            "title": "Hospitalist Practice 5",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 72,
            "content": "Admitted for community acquired pneumonia. Treated with lisinopril and amlodipine. Course was uncomplicated. Discharged to Admitted to floor on maintenance inhalers.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Hospitalist."
        },
        {
            "id": "med_dc_6",
            "specialty": "Hospitalist",
            "tier": "CORE",
            "title": "Hospitalist Practice 6",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 79,
            "content": "Hospital course: Patient admitted with dizziness, found to have generalized anxiety disorder. albuterol returning initiated. Condition improved. Discharge instructions: Admit to medicine.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Hospitalist."
        },
        {
            "id": "med_dc_7",
            "specialty": "Hospitalist",
            "tier": "CORE",
            "title": "Hospitalist Practice 7",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 78,
            "content": "Admitted for sepsis. Treated with lisinopril and amlodipine. Course was prolonged but stable. Discharged to Discharged home on new SSI regimen.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Hospitalist."
        },
        {
            "id": "med_dc_8",
            "specialty": "Hospitalist",
            "tier": "CORE",
            "title": "Hospitalist Practice 8",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 80,
            "content": "Admitted for community acquired pneumonia. Treated with albuterol returning. Course was uncomplicated. Discharged to Discharged to SNF on maintenance inhalers.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Hospitalist."
        },
        {
            "id": "med_dc_9",
            "specialty": "Hospitalist",
            "tier": "CORE",
            "title": "Hospitalist Practice 9",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 73,
            "content": "Hospital course: Patient admitted with right lower quadrant pain, found to have community acquired pneumonia. lisinopril and amlodipine initiated. Condition improved. Discharge instructions: Prepare for OR.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Hospitalist."
        },
        {
            "id": "med_dc_10",
            "specialty": "Hospitalist",
            "tier": "INTERMEDIATE",
            "title": "Hospitalist Practice 10",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 68,
            "content": "Hospital course: Patient admitted with acute chest pain, found to have generalized anxiety disorder. albuterol returning initiated. Condition improved. Discharge instructions: Consult cardiology.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Hospitalist."
        },
        {
            "id": "med_dc_11",
            "specialty": "Hospitalist",
            "tier": "CORE",
            "title": "Hospitalist Practice 11",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 78,
            "content": "Admitted for community acquired pneumonia. Treated with lisinopril and amlodipine. Course was prolonged but stable. Discharged to Discharged to SNF on maintenance inhalers.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Hospitalist."
        },
        {
            "id": "med_dc_12",
            "specialty": "Hospitalist",
            "tier": "INTERMEDIATE",
            "title": "Hospitalist Practice 12",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 82,
            "content": "Admitted for sepsis. Treated with IV fluids and insulin. Course was uncomplicated. Discharged to Admitted to floor on new SSI regimen.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Hospitalist."
        },
        {
            "id": "med_dc_13",
            "specialty": "Hospitalist",
            "tier": "INTERMEDIATE",
            "title": "Hospitalist Practice 13",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 71,
            "content": "Hospital course: Patient admitted with dizziness, found to have DKA. IV fluids and insulin initiated. Condition improved. Discharge instructions: Prepare for OR.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Hospitalist."
        },
        {
            "id": "med_dc_14",
            "specialty": "Hospitalist",
            "tier": "INTERMEDIATE",
            "title": "Hospitalist Practice 14",
            "recommendedMinutes": 5,
            "focusType": "TERMINOLOGY",
            "speedTargetWpm": 83,
            "content": "Hospital course: Patient admitted with persistent vomiting, found to have heart failure exacerbation. IV Rocephin initiated. Condition improved. Discharge instructions: Increase furosemide dose.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Hospitalist."
        },
        {
            "id": "med_dc_15",
            "specialty": "Hospitalist",
            "tier": "INTERMEDIATE",
            "title": "Hospitalist Practice 15",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 80,
            "content": "Admitted for community acquired pneumonia. Treated with lisinopril and amlodipine. Course was prolonged but stable. Discharged to Transferred to tertiary center on new SSI regimen.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Hospitalist."
        },
        {
            "id": "med_dc_16",
            "specialty": "Hospitalist",
            "tier": "INTERMEDIATE",
            "title": "Hospitalist Practice 16",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 84,
            "content": "Admitted for major depressive disorder. Treated with albuterol returning. Course was complicated by transient AKI. Discharged to Admitted to ICU on maintenance inhalers.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Hospitalist."
        },
        {
            "id": "med_dc_17",
            "specialty": "Hospitalist",
            "tier": "INTERMEDIATE",
            "title": "Hospitalist Practice 17",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 69,
            "content": "Admitted for major depressive disorder. Treated with lisinopril and amlodipine. Course was complicated by transient AKI. Discharged to Admitted to floor on oral antibiotics.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Hospitalist."
        },
        {
            "id": "med_dc_18",
            "specialty": "Hospitalist",
            "tier": "CORE",
            "title": "Hospitalist Practice 18",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 66,
            "content": "Hospital course: Patient admitted with syncope, found to have DKA. IV fluids and insulin initiated. Condition improved. Discharge instructions: Discharge with strict return precautions.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Hospitalist."
        },
        {
            "id": "med_dc_19",
            "specialty": "Hospitalist",
            "tier": "CORE",
            "title": "Hospitalist Practice 19",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 70,
            "content": "Hospital course: Patient admitted with persistent vomiting, found to have major depressive disorder. IV Rocephin initiated. Condition improved. Discharge instructions: Consult cardiology.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Hospitalist."
        },
        {
            "id": "med_dc_20",
            "specialty": "Hospitalist",
            "tier": "CORE",
            "title": "Hospitalist Practice 20",
            "recommendedMinutes": 5,
            "focusType": "ENDURANCE",
            "speedTargetWpm": 74,
            "content": "Admitted for sepsis. Treated with IV Rocephin. Course was complicated by transient AKI. Discharged to Admitted to floor on oral antibiotics.",
            "difficulty": "Specialist",
            "category": "Medical",
            "description": "Auto-generated practice drill for Hospitalist."
        }
    ]
};

export function getMedicalDrillsBySpecialty(specialty: string): Drill[] {
    // Map the selected specialty key to the keys generated
    const keyMap: Record<string, string> = {
        'emergency': 'emergency',
        'radiology': 'radiology',
        'cardiology': 'cardiology',
        'surgery': 'surgery',
        'psychiatry': 'psychiatry',
        'soap': 'soap',
        'discharge': 'discharge'
    };
    
    const mappedKey = keyMap[specialty.toLowerCase()] || specialty.toLowerCase();
    return medicalDrillPacks[mappedKey] || [];
}

export function getRandomMedicalDrill(tier?: 'CORE' | 'INTERMEDIATE' | 'SPECIALIST', specialty?: string): Drill | null {
    let pool: Drill[] = [];

    if (specialty) {
        pool = getMedicalDrillsBySpecialty(specialty);
    } else {
        Object.values(medicalDrillPacks).forEach(pack => pool.push(...pack));
    }

    if (tier) {
        pool = pool.filter(d => d.tier === tier);
    }

    if (pool.length === 0) return null;

    return pool[Math.floor(Math.random() * pool.length)];
}
